[1.18] A few random mappings made with scribe
ParchmentMC/Parchment pull request #101
Opened 2022-01-10 19:12 UTC by MelanX

While coding, I saw a few mappings. Here is what I changed.

2022-01-15 00:42 UTC, sciwhiz12 requested changes

2022-01-15 00:42 UTC, sciwhiz12 commented on data/net/minecraft/data/models/BlockModelGenerators.mapping
> +			ARG 1 textureMapping
Hmm, this looks like an edge case with inner classes (non-`static` nested classes), as the constructor of this method has two arguments, as can be seen in the correct mapping above (the enclosing class instance, and then the regular mandated parameters). @SizableShrimp, could you please take a look at this?

In the meantime, please remove this and the other added mapping in this class.

2022-01-16 05:12 UTC, sciwhiz12 commented on data/net/minecraft/data/models/BlockModelGenerators.mapping
> +			ARG 1 textureMapping
This issue is now being tracked at https://github.com/ParchmentMC/Scribe/issues/5.

2022-01-16 11:03 UTC, sciwhiz12 approved these changes

2022-01-17 08:11 UTC, SizableShrimp approved these changes

2022-01-21 08:40 UTC, merged