map net.minecraft.world.effect.MobEffectInstance
ParchmentMC/Parchment pull request #102
Opened 2022-01-14 22:06 UTC by v14d4n

2022-01-14 22:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ParchmentMC/Parchment?pullRequest=102) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ParchmentMC/Parchment?pullRequest=102) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ParchmentMC/Parchment?pullRequest=102) it.</sub>

2022-01-15 00:47 UTC, sciwhiz12 requested changes

2022-01-15 00:47 UTC, sciwhiz12 commented on data/net/minecraft/world/effect/MobEffectInstance.mapping
> +		ARG 1 effectInstance
According to our [conventions](https://github.com/ParchmentMC/Parchment/wiki/Mapping-Conventions), this copy constructor's parameter should be named `other`.

2022-01-15 00:47 UTC, sciwhiz12 commented on data/net/minecraft/world/effect/MobEffectInstance.mapping
> +		ARG 1 effectInstance
According to our [conventions](https://github.com/ParchmentMC/Parchment/wiki/Mapping-Conventions), this should be named `other`.

2022-01-15 00:47 UTC, sciwhiz12 commented on data/net/minecraft/world/effect/MobEffectInstance.mapping
> +		ARG 1 effectInstance
This is mapping the synthetic method -- the proper method that should be mapped here has the parameter of `MobEffectInstance`. For now, please remove this mapping (either manually or using the `sanitizeData` task).

2022-01-15 08:59 UTC, sciwhiz12 approved these changes

2022-01-16 08:04 UTC, SizableShrimp approved these changes

2022-01-21 08:39 UTC, merged