Some mappings I did awhile ago
ParchmentMC/Parchment pull request #103
Opened 2022-02-04 14:52 UTC by Lanse505

Here's some mappings I did awhile ago.
It should cover most of blaze3d, advancements and some client stuff.

2022-02-05 06:39 UTC, ChampionAsh5357 requested changes
There are probably a few more unmentioned that I overlooked, but these should cover the major points.

2022-02-05 06:39 UTC, ChampionAsh5357 commented on data/com/mojang/blaze3d/audio/Library.mapping
> +		ARG 1 deviceName
`AC10#alcOpenDevice` calls this `deviceSpecifier`

2022-02-05 06:39 UTC, ChampionAsh5357 commented on data/com/mojang/blaze3d/audio/Library.mapping
> +		ARG 0 deviceName
`AC10#alcOpenDevice` calls this `deviceSpecifier`

2022-02-05 06:39 UTC, ChampionAsh5357 commented on data/com/mojang/blaze3d/audio/Library.mapping
> +		ARG 0 deviceName
`AC10#alcOpenDevice` calls this `deviceSpecifier`

2022-02-05 06:39 UTC, ChampionAsh5357 commented on data/com/mojang/blaze3d/platform/GLX.mapping
> +		ARG 1 msg
`GLFWErrorCallbackI#invoke` refers to this as `error`, `description`

2022-02-05 06:39 UTC, ChampionAsh5357 commented on data/com/mojang/blaze3d/platform/GLX.mapping
> +		ARG 2 msg
`GLFWErrorCallbackI#invoke` refers to this as `error`, `description`

2022-02-05 06:39 UTC, ChampionAsh5357 commented on data/com/mojang/blaze3d/platform/GlStateManager.mapping
> +		ARG 2 transformationMatrix
Should also be `lighting` to match `Lighting` to which this is called from.

2022-02-05 06:39 UTC, ChampionAsh5357 commented on data/com/mojang/blaze3d/platform/MemoryTracker.mapping
> +		ARG 0 byteSize
Probably just `size`; however, either works.

2022-02-05 06:39 UTC, ChampionAsh5357 commented on data/com/mojang/blaze3d/platform/NativeImage.mapping
> +			ARG 1 unused
`context` as defined by `STBIWriteCallbackI`.

2022-02-05 06:39 UTC, ChampionAsh5357 commented on data/com/mojang/blaze3d/preprocessor/GlslPreprocessor.mapping
> +		ARG 1 hasSubDirectories
This would be using the full resource path from what I see, not whether subdirectories are present.

2022-02-05 06:39 UTC, ChampionAsh5357 commented on data/com/mojang/blaze3d/preprocessor/GlslPreprocessor.mapping
> +		ARG 2 index
What index? It seems this refers to the matcher on where it starts on the next available line.

2022-02-05 06:39 UTC, ChampionAsh5357 commented on data/com/mojang/blaze3d/vertex/VertexFormatElement.mapping
> +		ARG 1 elementCount
`elementIndex` I would think is more appropriate, it represents the index within the element list.

2022-02-05 06:39 UTC, ChampionAsh5357 commented on data/com/mojang/blaze3d/vertex/VertexFormatElement.mapping
> +		ARG 1 vertexSize
`elementIndex` I would think is more appropriate, it represents the index within the element list.

2022-02-05 06:39 UTC, ChampionAsh5357 commented on data/com/mojang/blaze3d/vertex/VertexFormatElement.mapping
> +		ARG 4 elementCount
`vertexSize`, may have inverted these two.

2022-02-05 06:39 UTC, ChampionAsh5357 commented on data/com/mojang/blaze3d/vertex/VertexFormatElement.mapping
> +			ARG 2 stateIndex
This is probably a better name than `elementIndex` mentioned above.

2022-02-05 06:39 UTC, ChampionAsh5357 commented on data/com/mojang/blaze3d/vertex/VertexFormatElement.mapping
> +			ARG 6 index
Wrong order and repeat for others:

`count`, `glType`, `vertexSize`, `offset`, `index`, `stateIndex`

2022-02-05 06:39 UTC, ChampionAsh5357 commented on data/com/mojang/blaze3d/vertex/VertexFormatElement.mapping
> +			ARG 1 elementCount
Repeat for others.

`index`, `stateIndex`

2022-02-05 06:39 UTC, ChampionAsh5357 commented on data/com/mojang/math/Matrix3f.mapping
> +		ARG 2 m11
These names really don't suit the variables:

ARG 0 is some corner of the quad, usually the lowest one of the matrix diagonal.
ARG 1 is the half of the sum of the two adjacent corners of the quad.
ARG 2 is the furthest point of the quad, usually the highest one of the matrix diagonal.

2022-02-05 06:39 UTC, ChampionAsh5357 commented on data/com/mojang/math/Matrix3f.mapping
> +		ARG 1 m10
Not good names here either.

It takes some quad corner on the diagonal and a point along the y adjacent side.

2022-02-05 06:39 UTC, ChampionAsh5357 commented on data/com/mojang/math/Matrix4f.mapping
> +		ARG 2 z
While these could be xyz, it may be better to have some description on how these types of matrices work in terms of doing mathematics.

2022-02-05 06:39 UTC, ChampionAsh5357 commented on data/com/mojang/math/SymmetricGroup3.mapping
> +		ARG 0 group
These both shouldn't be groups since one group is a lambda within another lambda. Probably the outer lambda should be `groups` with the inner being `group`.

2022-02-05 06:39 UTC, ChampionAsh5357 commented on data/net/minecraft/SharedConstants.mapping
> +		ARG 0 chunk
Not really the chunk, more of the `chunkPos`.

2022-02-05 06:39 UTC, ChampionAsh5357 commented on data/net/minecraft/Util.mapping
> +		ARG 0 pool
This is not a pool, this is the exception to thrown on termination.

2022-02-05 06:39 UTC, ChampionAsh5357 commented on data/net/minecraft/Util.mapping
> +		ARG 1 name
`strChar`

2022-02-05 06:39 UTC, ChampionAsh5357 commented on data/net/minecraft/Util.mapping
> +		ARG 0 pauser
`msg`

2022-02-05 06:39 UTC, ChampionAsh5357 commented on data/net/minecraft/Util.mapping
> +			ARG 1 value
`key`

2022-02-05 06:39 UTC, ChampionAsh5357 commented on data/net/minecraft/Util.mapping
> +			ARG 1 input1
`key1`

2022-02-05 06:39 UTC, ChampionAsh5357 commented on data/net/minecraft/Util.mapping
> +			ARG 2 input2
`key2`

2022-02-05 06:39 UTC, ChampionAsh5357 commented on data/net/minecraft/advancements/critereon/DeserializationContext.mapping
> +		ARG 0 tableResolver
`tableId`

2022-02-05 06:39 UTC, ChampionAsh5357 commented on data/net/minecraft/client/Camera.mapping
> +			ARG 2 leftScale
Reversed

2022-02-05 06:39 UTC, ChampionAsh5357 commented on data/net/minecraft/client/ClientRecipeBook.mapping
> +		ARG 0 recipes
`category`

2022-02-05 06:39 UTC, ChampionAsh5357 commented on data/net/minecraft/client/ClientRecipeBook.mapping
> +		ARG 3 recipes
`recipeList`

2022-02-05 06:39 UTC, ChampionAsh5357 commented on data/net/minecraft/client/ClientRecipeBook.mapping
> +		ARG 1 categories
`mainCategory`

2022-02-05 06:39 UTC, ChampionAsh5357 commented on data/net/minecraft/client/ClientRecipeBook.mapping
> +		ARG 2 categoryCollection
`subCategories`

2022-02-05 06:39 UTC, ChampionAsh5357 commented on data/net/minecraft/client/ClientTelemetryManager.mapping
> +		ARG 1 userId
`valueOpt`

2022-02-05 06:39 UTC, ChampionAsh5357 commented on data/net/minecraft/client/ClientTelemetryManager.mapping
> +		ARG 2 userId
`value`

2022-02-05 06:39 UTC, ChampionAsh5357 commented on data/net/minecraft/client/ClientTelemetryManager.mapping
> +		ARG 0 factory
`task`

2022-02-05 06:39 UTC, ChampionAsh5357 commented on data/net/minecraft/client/CycleOption.mapping
> +		ARG 2 minecraft
`button`

2022-02-05 06:39 UTC, ChampionAsh5357 commented on data/net/minecraft/client/CycleOption.mapping
> +		ARG 0 supplier
`value`

2022-02-05 06:39 UTC, ChampionAsh5357 commented on data/net/minecraft/client/FullscreenResolutionProgressOption.mapping
> +		ARG 2 val
`progress`

2022-02-05 06:39 UTC, ChampionAsh5357 commented on data/net/minecraft/client/ProgressOption.mapping
> +		ARG 0 sequence
`minecraft`

2022-02-05 06:39 UTC, ChampionAsh5357 commented on data/net/minecraft/client/Screenshot.mapping
> +		ARG 1 byteBuffer
`buffer`

2022-02-05 06:39 UTC, ChampionAsh5357 commented on data/net/minecraft/client/color/block/BlockTintCache.mapping
> +			ARG 1 level
`height`

2022-02-05 06:39 UTC, ChampionAsh5357 commented on data/net/minecraft/client/color/block/BlockTintCache.mapping
> +			ARG 1 layer
`newHeight`

2022-02-05 06:39 UTC, ChampionAsh5357 commented on data/net/minecraft/client/gui/Gui.mapping
> +		ARG 0 sideBar
`score`

2022-02-05 06:39 UTC, ChampionAsh5357 commented on data/net/minecraft/client/multiplayer/ClientChunkCache.mapping
> +		ARG 3 friendlyByteBuf
`buffer`

2022-02-05 06:39 UTC, ChampionAsh5357 commented on data/net/minecraft/client/multiplayer/ClientChunkCache.mapping
> +		ARG 5 consumer
Probably needs some docs.

2022-02-05 06:39 UTC, ChampionAsh5357 commented on data/net/minecraft/client/multiplayer/ClientLevel.mapping
> +		ARG 2 particle
`particleSettings`

2022-02-05 06:39 UTC, ChampionAsh5357 commented on data/net/minecraft/client/multiplayer/ClientLevel.mapping
> +		ARG 1 executor
`task`

2022-02-05 06:39 UTC, ChampionAsh5357 commented on data/net/minecraft/client/tutorial/BundleTutorial.mapping
> +		ARG 1 input
`carriedStack`

2022-02-05 06:39 UTC, ChampionAsh5357 commented on data/net/minecraft/client/tutorial/BundleTutorial.mapping
> +		ARG 2 bundle
`slottedStack`

2022-02-05 06:39 UTC, ChampionAsh5357 commented on data/net/minecraft/client/tutorial/Tutorial.mapping
> +		ARG 2 bundle
`carriedStack`, `slottedStack`

2022-02-05 06:39 UTC, ChampionAsh5357 commented on data/net/minecraft/client/renderer/RenderType.mapping
> +		ARG 3 mdoe
`mode`

2022-02-05 06:39 UTC, ChampionAsh5357 commented on data/net/minecraft/client/renderer/RenderType.mapping
> +		ARG 1 cull
This is not cull, it just affects whether the rendering affects the outline of the object.

2022-02-05 06:39 UTC, ChampionAsh5357 commented on data/net/minecraft/client/renderer/RenderType.mapping
> +			ARG 1 type
`texture`, `cullState`

2022-02-05 06:39 UTC, ChampionAsh5357 commented on data/net/minecraft/client/renderer/LevelRenderer.mapping
> +		ARG 1 chunk
`renderChunk`, it's not really the same as a normal chunk. Same for below.

2022-02-05 06:39 UTC, ChampionAsh5357 commented on data/net/minecraft/client/renderer/LevelRenderer.mapping
> +		ARG 0 progress
`progressPos`

2022-02-05 06:39 UTC, ChampionAsh5357 commented on data/net/minecraft/client/renderer/LevelRenderer.mapping
> +		ARG 1 val
`info`

2022-02-05 06:39 UTC, ChampionAsh5357 commented on data/net/minecraft/client/renderer/LevelRenderer.mapping
> +		ARG 1 chunkInfo
`chunkInfos`

2022-02-05 06:39 UTC, ChampionAsh5357 commented on data/net/minecraft/client/multiplayer/ClientPacketListener.mapping
> +		ARG 1 category
`recipeCollection`

2022-02-05 06:39 UTC, ChampionAsh5357 commented on data/net/minecraft/client/multiplayer/ClientPacketListener.mapping
> +		ARG 2 entity
`blockEntity`

2022-02-05 06:39 UTC, ChampionAsh5357 commented on data/net/minecraft/client/multiplayer/ClientPacketListener.mapping
> +		ARG 5 lightSetX
`yMask`

2022-02-05 06:39 UTC, ChampionAsh5357 commented on data/net/minecraft/client/multiplayer/ClientPacketListener.mapping
> +		ARG 6 lightSetZ
`emptyYMask`

2022-02-05 06:39 UTC, ChampionAsh5357 commented on data/net/minecraft/client/multiplayer/ClientPacketListener.mapping
> +		ARG 7 layerIterator
`updatesIterator`

2022-02-05 06:39 UTC, ChampionAsh5357 commented on data/net/minecraft/client/renderer/GameRenderer.mapping
> +		ARG 0 entity
`checkingEntity`, `entity` already exists as a local var.

2022-02-05 06:39 UTC, ChampionAsh5357 commented on data/net/minecraft/client/renderer/GameRenderer.mapping
> +		ARG 1 file
`worldScreenshtFile`, explicit is better

2022-02-05 06:39 UTC, ChampionAsh5357 commented on data/net/minecraft/client/Options.mapping
> +		ARG 0 value
`entry`

2022-02-05 06:39 UTC, ChampionAsh5357 commented on data/net/minecraft/client/Options.mapping
> +		ARG 1 category
`source`

2022-02-05 06:39 UTC, ChampionAsh5357 commented on data/net/minecraft/client/Options.mapping
> +		ARG 0 name
status

2022-02-05 06:39 UTC, ChampionAsh5357 commented on data/net/minecraft/client/Options.mapping
> +		ARG 0 name
`status`

2022-02-05 06:39 UTC, ChampionAsh5357 commented on data/net/minecraft/client/Options.mapping
> +		ARG 0 name
`compressedPackList`

2022-02-05 06:39 UTC, ChampionAsh5357 commented on data/net/minecraft/client/Options.mapping
> +			ARG 1 name
`key`

2022-02-05 06:39 UTC, ChampionAsh5357 commented on data/net/minecraft/client/StringSplitter.mapping
> +		ARG 1 messageLength
Pretty sure this is something else, but unsure.

2022-02-05 06:39 UTC, ChampionAsh5357 commented on data/net/minecraft/client/StringSplitter.mapping
> +			ARG 2 iterations
This also seems wrong as a name, but unsure what to replace with.

2022-02-05 06:39 UTC, ChampionAsh5357 commented on data/net/minecraft/client/Option.mapping
> +		ARG 2 particles
Probably `status`

2022-02-05 06:39 UTC, ChampionAsh5357 commented on data/net/minecraft/client/Option.mapping
> +		ARG 0 value
`status`

2022-02-05 06:39 UTC, ChampionAsh5357 commented on data/net/minecraft/client/Option.mapping
> +		ARG 2 renderClouds
`status`

2022-02-05 21:48 UTC, ChampionAsh5357 requested changes
I think this should be fine now except for one change.

2022-02-05 21:48 UTC, ChampionAsh5357 commented on data/net/minecraft/client/ClientRecipeBook.mapping
> +		ARG 0 recipes
`category`

2022-02-08 09:19 UTC, sciwhiz12 approved these changes

2022-02-10 14:30 UTC, ChampionAsh5357 approved these changes

2022-02-13 02:01 UTC, merged