Partially document the entity attribute system.
ParchmentMC/Parchment pull request #11
Opened 2021-06-22 02:28 UTC by Darkhax

2021-06-22 02:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ParchmentMC/Parchment?pullRequest=11) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ParchmentMC/Parchment?pullRequest=11) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ParchmentMC/Parchment?pullRequest=11) it.</sub>

2021-06-22 02:45 UTC, sciwhiz12 submitted a review, later dismissed
Looks fine to me, though I do have one suggestion.

2021-06-22 02:45 UTC, sciwhiz12 commented on data/net/minecraft/world/entity/ai/attributes/Attributes.mapping
> +		COMMENT @return The attribute that was registered.
Might want to include a `@see` or `@link` referring to `Registry#ATTRIBUTE`.

2021-06-22 15:02 UTC, OrionDevelopment requested changes

2021-06-22 15:02 UTC, marchermans commented on data/net/minecraft/world/entity/ai/attributes/Attribute.mapping
> +		ARG 1 description
Most likely this should be `descriptionId`

2021-06-22 15:02 UTC, marchermans commented on data/net/minecraft/world/entity/ai/attributes/Attribute.mapping
> +		COMMENT Gets the localization key of the attribute.
This comment is not consistent.
It should reference the `descriptionId` and only make a note of the fact that this is commonly used as the translation key, in the same way you did for the field.

2021-06-22 15:02 UTC, marchermans commented on data/net/minecraft/world/entity/ai/attributes/Attributes.mapping
> +		COMMENT @return The attribute that was registered.
Agreed

2021-06-22 15:02 UTC, marchermans commented on data/net/minecraft/world/entity/ai/attributes/RangedAttribute.mapping
> +	COMMENT Defines an entity ettribute that is limited to a range of values.
Missing `@see Attribute`

2021-06-22 15:02 UTC, OrionDevelopment commented on data/net/minecraft/world/entity/ai/attributes/RangedAttribute.mapping
> +		ARG 1 description
Should be `descriptionId` since this is passed to the `Attribute` class.

2021-06-22 15:02 UTC, OrionDevelopment commented on data/net/minecraft/world/entity/ai/attributes/RangedAttribute.mapping
>  	METHOD sanitizeValue (D)D
You need a documentation line here at least.
Since the logic changes here for the sanitation.

2021-06-25 08:33 UTC, mcenderdragon approved these changes

2021-06-25 08:47 UTC, OrionDevelopment approved these changes

2021-06-25 18:49 UTC, jaredlll08 approved these changes

2021-06-27 09:24 UTC, merged