Map some datapack related functions
ParchmentMC/Parchment pull request #110
Opened 2022-02-25 23:06 UTC by joshyrobot

2022-02-25 23:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ParchmentMC/Parchment?pullRequest=110) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ParchmentMC/Parchment?pullRequest=110) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ParchmentMC/Parchment?pullRequest=110) it.</sub>

2022-03-05 04:57 UTC, sciwhiz12 requested changes
Looks good apart from three parameter changes for the pack's `title`.

2022-03-05 04:57 UTC, sciwhiz12 commented on data/net/minecraft/server/packs/repository/Pack.mapping
> +		ARG 2 component
This seems to be assigned to the `title` field.

2022-03-05 04:57 UTC, sciwhiz12 commented on data/net/minecraft/server/packs/repository/Pack.mapping
> +		ARG 4 component
This seems to be assigned to the `title` field.

2022-03-05 04:57 UTC, sciwhiz12 commented on data/net/minecraft/server/packs/repository/Pack.mapping
> +			ARG 2 component
This is likely to be the `title` of the pack.

2022-03-05 05:26 UTC, sciwhiz12 approved these changes

2022-03-05 11:50 UTC, MelanX approved these changes

2022-03-05 11:52 UTC, Lanse505 approved these changes

2022-03-06 11:31 UTC, merged