[1.18.x] Some misc. mappings
ParchmentMC/Parchment pull request #115
Opened 2022-03-27 03:26 UTC by SizableShrimp

2022-03-27 07:20 UTC, sciwhiz12 requested changes

2022-03-27 07:20 UTC, sciwhiz12 commented on data/net/minecraft/world/item/alchemy/PotionUtils.mapping
> +		COMMENT If it fails, returns {@code net.minecraft.world.item.alchemy.Potions#EMPTY Potions#EMPTY}
As a matter of consistency, could you please apply the javadoc (modified accordingly) to the `getPotion(CompoundTag)` method?

2022-04-20 14:33 UTC, alcatrazEscapee approved these changes, later dismissed
I'll echo sci's feedback but otherwise looks good.

2022-04-20 14:56 UTC, alcatrazEscapee approved these changes

2022-04-20 14:56 UTC, alcatrazEscapee commented
@sciwhiz12 Poking for approval.

2022-04-21 07:05 UTC, sciwhiz12 approved these changes

2022-04-23 07:48 UTC, merged