Added various mappings
ParchmentMC/Parchment pull request #127
Opened 2022-06-23 15:57 UTC by PiTheGuy

2022-06-23 16:04 UTC, PiTheGuy commented
Found validation errors, need to fix before this is ready for review

2022-06-23 17:46 UTC, PiTheGuy commented
This pull request is ready,

2022-06-23 17:50 UTC, alcatrazEscapee commented
So just to clarify one point: the validation error with methods like `compareTo` is due to a quirk with how Enigma ends up mapping methods - it maps the synthetic bridge method rather than the user visible method. Meaning you mapped `compareTo(Object)` instead of `<T> compareTo(T)`. The fix for this is manually changing the signature, in the `.mapping` file, if you so desire.

@sciwhiz12 wrote a whole article on synthetic bouncers in Java and how they apply here if he wants to plug it :)

2022-06-23 18:00 UTC, PiTheGuy commented
Ok, I'll fix that real quick

2022-06-23 18:31 UTC, PiTheGuy commented
What do I change the signature to?

2022-06-23 19:36 UTC, alcatrazEscapee commented
`compareTo(T t)` is from `Comparable<T>`, which will be erased to whatever the type bound on `Comparable`  is. Then use the fully qualified descriptor, so if it implements `Comparable<Foo>`, you want to replace the `Object` with `Foo`

That said, if you don't want to screw around with the raw .mapping files, it's entirely fine to just omit them.

2022-06-23 19:57 UTC, alcatrazEscapee requested changes
Each time I went to comment that a parameter name was not great, I went and looked it up, and it was because it was matching an existing mojmap name. Every *single* time.

The vast majority of this PR is datafixer and schema names, of which there's about two reviewable changes spread over some two hundred files it seems.

Just one comment, as if we're changing this javadoc we might as well properly fix it.

2022-06-23 19:57 UTC, alcatrazEscapee commented on data/net/minecraft/server/commands/DefaultGameModeCommands.mapping
> +		COMMENT Set Gametype of the player who ran the command
```suggestion
		COMMENT Sets the {@link net.minecraft.world.level.GameType} of the player who ran the command.
```

2022-06-23 20:37 UTC, alcatrazEscapee commented
Two quick comments: please don't keep adding just everything-and-the-kitchen-sink to this PR, as larger PRs make it harder to review them.

Additionally, please don't continue to add mappings after you've stated a PR is ready for review, because as again, it makes it harder to review.

2022-06-23 21:07 UTC, PiTheGuy commented
Noted, I'll make a new PR from now on

2022-06-26 16:42 UTC, alcatrazEscapee approved these changes

2022-06-26 16:44 UTC, merged