Various mappings in data/com/mojang/realmsclient
ParchmentMC/Parchment pull request #142
Opened 2022-07-03 18:16 UTC by PiTheGuy

2022-07-08 14:44 UTC, Lanse505 requested changes

2022-07-08 14:44 UTC, Lanse505 commented on data/com/mojang/realmsclient/client/FileDownload.mapping
> +		ARG 2 worldName
Order of arguments are: ``download, worldName, status, source``

2022-07-08 14:44 UTC, Lanse505 commented on data/com/mojang/realmsclient/gui/screens/RealmsPlayerScreen.mapping
> +			ARG 1 player
this should be ``index`` to match super call.

2022-07-08 16:40 UTC, PiTheGuy commented
Suggestions have been applied

2022-07-10 01:06 UTC, Lanse505 approved these changes
lgtm

2022-07-10 01:12 UTC, merged