Various mappings in net/minecraft/client/renderer
ParchmentMC/Parchment pull request #143
Opened 2022-07-04 19:32 UTC by PiTheGuy

2022-07-09 08:43 UTC, sciwhiz12 requested changes

2022-07-09 08:43 UTC, sciwhiz12 commented on data/net/minecraft/client/renderer/entity/PandaRenderer.mapping
> +		ARG 4 partialTicks
```suggestion
		ARG 4 partialTick
```

2022-07-09 08:43 UTC, sciwhiz12 commented on data/net/minecraft/client/renderer/entity/layers/ItemInHandLayer.mapping
> +		ARG 7 combinedLight
```suggestion
		ARG 7 packedLight
```

2022-07-09 15:26 UTC, PiTheGuy commented
All suggestions have been applied.

2022-07-10 01:04 UTC, sciwhiz12 approved these changes

2022-07-10 01:04 UTC, merged