Various mappings in net/minecraft/server
ParchmentMC/Parchment pull request #144
Opened 2022-07-05 19:18 UTC by PiTheGuy

This PR adds various mappings to net/minecraft/server/level and net/minecraft/server/commands

2022-07-09 08:06 UTC, sciwhiz12 requested changes

2022-07-09 08:06 UTC, sciwhiz12 commented on data/net/minecraft/server/commands/AttributeCommand.mapping
> +		ARG 3 scale
```suggestion
		ARG 3 value
```

2022-07-09 15:22 UTC, PiTheGuy commented on data/net/minecraft/server/commands/AttributeCommand.mapping
> +		ARG 3 scale
I guess I wasn't paying enough attention for this one

2022-07-09 15:23 UTC, PiTheGuy commented
Applied suggestion

2022-07-10 01:03 UTC, sciwhiz12 approved these changes

2022-07-10 01:04 UTC, merged