Various mappings in net/minecraft/network
ParchmentMC/Parchment pull request #146
Opened 2022-07-08 20:07 UTC by PiTheGuy

2022-07-09 09:51 UTC, sciwhiz12 requested changes

2022-07-09 09:51 UTC, sciwhiz12 commented on data/net/minecraft/network/protocol/game/DebugPackets.mapping
> +		ARG 2 location
Better to follow `ClientboundCustomPayloadPacket`'s name for this, which differentiates it from positional location.
```suggestion
		ARG 2 identifier
```

2022-07-09 15:18 UTC, PiTheGuy commented
Suggestion applied

2022-07-10 01:01 UTC, sciwhiz12 approved these changes

2022-07-10 01:02 UTC, merged