Refactor worldPosition -> pos, and cleanup some misc. javadocs.
ParchmentMC/Parchment pull request #150
Opened 2022-07-10 20:36 UTC by alcatrazEscapee

Continuing from https://github.com/ParchmentMC/Parchment/pull/136#discussion_r912521702, it was decided to switch `worldPosition` -> `pos`, for the reasons outlined in said comment (consistency with public accessor `getBlockPos` over protected field `worldPosition`, `worldPosition` itself being a weird name only used by block entities, and consistency with other `BlockPos` arguments). This simply makes that change across all existing mapped block entities.

While I was going through these, I edited a few javadocs, expanding, fixing formatting (sentences), or just general cleanup.

2022-07-12 09:06 UTC, Harleyoc1 commented on data/net/minecraft/world/level/block/entity/HopperBlockEntity.mapping
>  		ARG 1 direction
I would advise doing `{@code container}` here since it's a reference to a parameter. 
To be consistent with your other changes I would also change `false` to `{@code false}`.

2022-07-12 22:04 UTC, Harleyoc1 approved these changes, later dismissed

2022-07-14 06:11 UTC, sciwhiz12 requested changes
`net\minecraft\world\level\block\piston\PistonMovingBlockEntity` also needs to be corrected from `worldPosition` parameter names to `pos`.

2022-07-14 06:11 UTC, sciwhiz12 commented on data/net/minecraft/world/level/block/entity/BannerBlockEntity.mapping
>  		ARG 1 worldPosition
Missed this one.
```suggestion
		ARG 1 pos
```

2022-07-14 12:49 UTC, sciwhiz12 approved these changes

2022-07-14 12:50 UTC, merged