More mappings for net/minecraft/level
ParchmentMC/Parchment pull request #153
Opened 2022-07-14 19:56 UTC by PiTheGuy

This PR adds mappings for net/minecraft/world/level/chunk and net/minecraft/world/level/pathfinder

2022-07-14 19:57 UTC, PiTheGuy commented on data/net/minecraft/world/level/chunk/ProtoChunk.mapping
> -		ARG 1 pos
This was changed to match the super class.

2022-07-28 18:31 UTC, Lanse505 requested changes
Looks good to me minus one change

2022-07-28 18:31 UTC, Lanse505 commented on data/net/minecraft/world/level/chunk/UpgradeData.mapping
> +		ARG 0 tag
``tag, identifier, valueFunction, ticks``

2022-07-28 18:38 UTC, PiTheGuy commented on data/net/minecraft/world/level/chunk/UpgradeData.mapping
> +		ARG 0 tag
Changed

2022-07-28 18:44 UTC, Lanse505 approved these changes

2022-07-31 10:14 UTC, merged