Various mappings for net/minecraft/world/level/levelgen
ParchmentMC/Parchment pull request #159
Opened 2022-08-08 19:45 UTC by PiTheGuy

2022-08-11 19:35 UTC, PiTheGuy commented
Converted to draft while I update this to 1.19

2022-08-11 19:48 UTC, PiTheGuy commented
I changed my mind. I have no idea what I'm doing.

2022-08-14 07:20 UTC, sciwhiz12 requested changes

2022-08-14 07:20 UTC, sciwhiz12 commented on data/net/minecraft/world/level/levelgen/SurfaceSystem.mapping
> +		ARG 0 randomSource
Current convention is to name `RandomSource` parameters as `random`.
```suggestion
		ARG 0 random
```

2022-08-14 07:20 UTC, sciwhiz12 commented on data/net/minecraft/world/level/levelgen/SurfaceSystem.mapping
> +		ARG 0 randomSource
```suggestion
		ARG 0 random
```

2022-08-14 07:20 UTC, sciwhiz12 commented on data/net/minecraft/world/level/levelgen/structure/placement/RandomSpreadType.mapping
> +		ARG 1 randomSource
```suggestion
		ARG 1 random
```

2022-08-14 17:47 UTC, sciwhiz12 approved these changes

2022-08-14 17:47 UTC, merged