Fix some typos
ParchmentMC/Parchment pull request #172
Opened 2022-08-28 16:25 UTC by noeppi-noeppi

2022-08-28 20:12 UTC, Harleyoc1 requested changes

2022-08-28 20:12 UTC, Harleyoc1 commented on data/net/minecraft/client/KeyMapping.mapping
> +		COMMENT Returns a supplier which gets a keybinds current binding (eg, <code>key.forward</code> returns <samp>W</samp> by default), or the keybind's name if no such keybind exists (eg, <code>key.inv
Is the original not correct here? It's a possessive?

2022-08-28 20:12 UTC, Harleyoc1 commented on data/net/minecraft/client/player/LocalPlayer.mapping
> +		ARG 1 potioneffect
Probably best to change this to just `effect` or `mobEffect` given the class is no longer called a potion effect.

2022-08-28 20:12 UTC, Harleyoc1 commented on data/net/minecraft/server/players/GameProfileCache.mapping
> +		COMMENT Get a player's GameProfile given their username. Mojangs server's will be contacted if the entry is not cached locally.
In this case I think the original is wrong but it should be changed the other way around: `Mojang's servers`.

2022-08-28 20:12 UTC, Harleyoc1 commented on data/net/minecraft/world/entity/Mob.mapping
> +		COMMENT The speed it takes to move the entitylivings head rotation through the faceEntity method.
Again I think the original is correct here. 
May as well also change it to `mob` rather than `entityliving`.

2022-08-28 20:12 UTC, Harleyoc1 commented on data/net/minecraft/world/entity/animal/Dolphin.mapping
> +		COMMENT The speed it takes to move the entitylivings rotationPitch through the faceEntity method. This is only currently use in wolves.
Same comment as above.

2022-08-28 20:12 UTC, Harleyoc1 commented on data/net/minecraft/world/entity/animal/Wolf.mapping
> +		COMMENT The speed it takes to move the entitylivings rotationPitch through the faceEntity method. This is only currently use in wolves.
Same comment as above.

2022-08-28 20:12 UTC, Harleyoc1 commented on data/net/minecraft/world/entity/boss/enderdragon/EnderDragon.mapping
> +		COMMENT Updates the state of the enderdragons current endercrystal.
Same case with possessives as above. I would also change this to just `dragon`.

2022-08-28 20:12 UTC, Harleyoc1 commented on data/net/minecraft/world/entity/boss/enderdragon/EnderDragon.mapping
> +		COMMENT Updates the state of the enderdragons current endercrystal.
Same case with possessives as above. I would also change this to just `dragon`.

2022-08-28 20:12 UTC, Harleyoc1 commented on data/net/minecraft/world/entity/boss/enderdragon/EnderDragon.mapping
> +		COMMENT Updates the state of the enderdragons current endercrystal.
Same case with possessives as above. I would also change this to just `dragon`.

2022-08-28 20:12 UTC, Harleyoc1 commented on data/net/minecraft/world/entity/boss/wither/WitherBoss.mapping
> +		COMMENT Initializes this Withers explosion sequence and makes it invulnerable. Called immediately after spawning.
Same case as above with possessives.

2022-08-28 20:12 UTC, Harleyoc1 commented on data/net/minecraft/world/entity/monster/Guardian.mapping
> +		COMMENT The speed it takes to move the entitylivings rotationPitch through the faceEntity method. This is only currently use in wolves.
Same comment as above.

2022-08-28 20:12 UTC, Harleyoc1 commented on data/net/minecraft/world/entity/monster/Shulker.mapping
> +		COMMENT The speed it takes to move the entitylivings rotationPitch through the faceEntity method. This is only currently use in wolves.
Same comment as above.

2022-08-28 20:12 UTC, Harleyoc1 commented on data/net/minecraft/world/entity/monster/Slime.mapping
> +		COMMENT The speed it takes to move the entitylivings rotationPitch through the faceEntity method. This is only currently use in wolves.
Same comment as above.

2022-08-28 20:12 UTC, Harleyoc1 commented on data/net/minecraft/world/item/Item.mapping
> +		COMMENT If this itemstacks item is a crossbow
Same case with possessives. I would also change this to just `stack`.

2022-08-28 20:12 UTC, Harleyoc1 commented on data/net/minecraft/world/level/biome/Biome.mapping
> +		COMMENT Gets a floating point representation of this biomes rainfall
Same case as above with possessives.

2022-08-28 20:12 UTC, Harleyoc1 commented on data/net/minecraft/world/level/levelgen/WorldgenRandom.mapping
> +			COMMENT The cumulative index of the generating feature within the biomes list of features.
Same case as above with possessives.

2022-09-01 12:55 UTC, Harleyoc1 approved these changes, later dismissed

2022-09-03 06:33 UTC, sciwhiz12 requested changes

2022-09-03 06:33 UTC, sciwhiz12 commented on data/net/minecraft/server/players/PlayerList.mapping
> +		COMMENT self explanatory
We should remove this comment entirely, since it is entirely useless.

2022-09-03 06:33 UTC, sciwhiz12 commented on data/net/minecraft/world/item/enchantment/Enchantment.mapping
> +		COMMENT @return The name of the enchantment with the level append to the end.
I think the typo to be corrected here is `appened` to `appended`, with a missing `d`.
```suggestion
		COMMENT @return The name of the enchantment with the level appended to the end.
```

2022-09-03 09:10 UTC, sciwhiz12 approved these changes
:shipit:

2022-09-03 09:10 UTC, merged