[1.19.x] Minor update for class changes
ParchmentMC/Parchment pull request #178
Opened 2022-10-03 06:43 UTC by tmvkrpxl0

This PR changes all `TileEntity` to `BlockEntity`, for both javadoc and parameter names
and updates javadoc of `Item#interactLivingEntity` so that it better matches with class changes
I have removed parameter names of `{Server, Local}Player#openTextEdit` because these were still `TileEntity`, and was shadowed by `Player#openTextEdit` with correct parameter name.

2022-10-03 11:12 UTC, alcatrazEscapee requested changes

2022-10-03 11:12 UTC, alcatrazEscapee commented on data/net/minecraft/world/item/DyeItem.mapping
> +		COMMENT Try interacting with givein entity. Return {@code InteractionResult.PASS} if nothing should happen.
```suggestion
		COMMENT Try interacting with given entity. Return {@code InteractionResult.PASS} if nothing should happen.
```

2022-10-03 11:12 UTC, alcatrazEscapee commented on data/net/minecraft/world/item/Item.mapping
> +		COMMENT Try interacting with givein entity. Return {@code InteractionResult.PASS} if nothing should happen.
```suggestion
		COMMENT Try interacting with given entity. Return {@code InteractionResult.PASS} if nothing should happen.
```

2022-10-03 11:12 UTC, alcatrazEscapee commented on data/net/minecraft/world/item/NameTagItem.mapping
> +		COMMENT Try interacting with givein entity. Return {@code InteractionResult.PASS} if nothing should happen.
```suggestion
		COMMENT Try interacting with given entity. Return {@code InteractionResult.PASS} if nothing should happen.
```

2022-10-03 11:12 UTC, alcatrazEscapee commented on data/net/minecraft/world/item/SaddleItem.mapping
> +		COMMENT Try interacting with givein entity. Return {@code InteractionResult.PASS} if nothing should happen.
```suggestion
		COMMENT Try interacting with given entity. Return {@code InteractionResult.PASS} if nothing should happen.
```

2022-10-03 23:19 UTC, tmvkrpxl0 commented
Bruh I didn't see I wrote givein instead of given until now

2022-10-04 02:23 UTC, alcatrazEscapee approved these changes

2022-10-04 14:37 UTC, merged