redstone signal javadocs and related refactors
ParchmentMC/Parchment pull request #200
Opened 2023-04-02 20:48 UTC by SpaceWalkerRS

2023-04-02 20:48 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ParchmentMC/Parchment?pullRequest=200) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ParchmentMC/Parchment?pullRequest=200) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ParchmentMC/Parchment?pullRequest=200) it.</sub>

2023-06-24 03:02 UTC, sciwhiz12 requested changes
Hello! Sorry for the delay in your PR getting a review; I've been a tad busy due to personal commitments and some issues in the toolchain (which were fixed today).

Looks fine to me; just have that one grammar fix. 

(Also, the fact that redstone diodes have the opposite of the instinctual facing -- their facing is aligned to ther _input_, rather than their _output_ as with all other blocks like dispensers, droppers, hoppers, etc. -- is fun _and_ confusing. 😄)

2023-06-24 03:02 UTC, sciwhiz12 commented on data/net/minecraft/world/level/block/state/BlockBehaviour.mapping
> +		COMMENT indirect the neighbors, if any.
Looks like a simple switch-a-roo of words.
```suggestion
		COMMENT the indirect neighbors, if any.
```

2023-06-24 08:47 UTC, SpaceWalkerRS commented
No worries, thanks for the review! There have been some changes to this code in 1.20 so look forward to another PR for that ^^

> (Also, the fact that redstone diodes have the opposite of the instinctual facing -- their facing is aligned to ther input, rather than their output as with all other blocks like dispensers, droppers, hoppers, etc. -- is fun and confusing. 😄)

Yeah that's quite baffling to be honest - I don't know if it's a remnant of old Notch code or what, but surely that's something that could/would have been fixed in 1.8, if not during The Flattening? Oh well.

2023-06-25 03:00 UTC, sciwhiz12 approved these changes

2023-06-25 03:01 UTC, merged