Render Code - Mappings & JavaDocs
ParchmentMC/Parchment pull request #218
Opened 2023-07-11 22:17 UTC by Lanse505

2023-07-12 14:46 UTC, PiTheGuy requested changes

2023-07-12 14:46 UTC, PiTheGuy commented on data/net/minecraft/client/gui/GuiGraphics.mapping
> +		ARG 9 vheight
```suggestion
		ARG 9 vHeight
```

2023-07-15 13:41 UTC, alcatrazEscapee commented
"minor changes", *minor changes* my ass. Maty you should know Simon can't just make a minor changes PR, he has to fully document the entirety of client code in one go! /j

2023-07-15 15:53 UTC, PiTheGuy requested changes

2023-07-15 15:53 UTC, PiTheGuy commented on data/net/minecraft/client/gui/GuiGraphics.mapping
> +		ARG 12 textureWidth
```suggestion
		ARG 12 textureX
```

2023-07-15 15:53 UTC, PiTheGuy commented on data/net/minecraft/client/gui/GuiGraphics.mapping
> +		ARG 7 yOffset
```suggestion
		ARG 7 vOffset
```

2023-07-15 15:53 UTC, PiTheGuy commented on data/net/minecraft/client/gui/GuiGraphics.mapping
> +			COMMENT The y-coordinate of the top-left corner of the source position.
The Javadoc on these parameters seems inconsistent with their name. `uOffset` usually represents the x-coordinate of the top-left corner, not the width.

2023-07-15 15:53 UTC, PiTheGuy commented on data/net/minecraft/client/gui/GuiGraphics.mapping
> +			COMMENT The y-coordinate of the top-left corner of the source position.
Just as above, the Javadoc on these parameters seems inconsistent with their name. `textureWidth` should not represent an x-coordinate.

2023-07-16 20:24 UTC, PiTheGuy requested changes

2023-07-16 20:24 UTC, PiTheGuy commented on data/net/minecraft/client/gui/Gui.mapping
> +			COMMENT the X-coordinate for rendering the jump meter.
The x in `x-coordinate` has inconsistent capitalization across the file (sometimes it's `x-coordinate` and sometimes it's `X-coordinate`. I think it should be consistent.

2023-07-16 20:24 UTC, PiTheGuy commented on data/net/minecraft/client/gui/Gui.mapping
> +			COMMENT the HitResult object representing the result of a ray trace operation.
```suggestion
			COMMENT the {@link HitResult} object representing the result of a ray trace operation.
```

2023-07-16 20:24 UTC, PiTheGuy commented on data/net/minecraft/client/gui/Gui.mapping
>  		COMMENT @return The maximum number of hearts representing the vehicle's health, or 0 if the mount entity is null or does not show vehicle health.
The first word after a `@return` tag should not be capitalized.

2023-07-16 20:24 UTC, PiTheGuy commented on data/net/minecraft/client/gui/components/tabs/TabNavigationBar.mapping
> +		COMMENT {@return The screen rectangle occupied by the GUI element.}
```suggestion
		COMMENT {@return The {@link ScreenRectangle} occupied by the GUI element.}
```

2023-07-16 20:45 UTC, PiTheGuy submitted a review, later dismissed

2023-07-16 20:49 UTC, Matyrobbrt requested changes, later dismissed
Haven't taken a look at the contents, just at the formatting around inline `@return` tags.

2023-07-16 20:49 UTC, Matyrobbrt commented on data/net/minecraft/client/gui/ComponentPath.mapping
> +			COMMENT {@return the child path associated with this path.}
```suggestion
			COMMENT {@return the child path associated with this path}
```

2023-07-16 20:49 UTC, Matyrobbrt commented on data/net/minecraft/client/gui/ComponentPath.mapping
> +			COMMENT {@return the {@code GuiEventListener} component associated with this component path.}
```suggestion
			COMMENT {@return the {@code GuiEventListener} component associated with this component path}
```

2023-07-16 20:49 UTC, Matyrobbrt commented on data/net/minecraft/client/gui/narration/NarratableEntry.mapping
> +		COMMENT {@return {@code true} if the element is active, {@code false} otherwise.}
```suggestion
		COMMENT {@return {@code true} if the element is active, {@code false} otherwise}
```

2023-07-16 20:49 UTC, Matyrobbrt commented on data/net/minecraft/client/gui/narration/NarratableEntry.mapping
> +		COMMENT {@return the narration priority.}
```suggestion
		COMMENT {@return the narration priority}
```

2023-07-16 20:49 UTC, Matyrobbrt commented on data/net/minecraft/client/gui/ComponentPath.mapping
> +		COMMENT {@return the {@code GuiEventListener} component associated with this component path.}
```suggestion
		COMMENT {@return the {@code GuiEventListener} component associated with this component path}
```

2023-07-16 20:49 UTC, Matyrobbrt commented on data/net/minecraft/client/gui/Gui.mapping
> +		COMMENT {@return the {@link BossHealthOverlay} instance associated with the client.}
```suggestion
		COMMENT {@return the {@link BossHealthOverlay} instance associated with the client}
```

2023-07-16 20:49 UTC, Matyrobbrt commented on data/net/minecraft/client/gui/Gui.mapping
> +		COMMENT {@return a pointer to the persistent Chat GUI, containing all previous chat messages and such.}
```suggestion
		COMMENT {@return a pointer to the persistent Chat GUI, containing all previous chat messages and such}
```

2023-07-16 20:49 UTC, Matyrobbrt commented on data/net/minecraft/client/gui/Gui.mapping
> +		COMMENT {@return the {@link Font} used for rendering text in the GUI.}
```suggestion
		COMMENT {@return the {@link Font} used for rendering text in the GUI}
```

2023-07-16 20:49 UTC, Matyrobbrt commented on data/net/minecraft/client/gui/Gui.mapping
> +		COMMENT {@return the number of GUI ticks elapsed.}
```suggestion
		COMMENT {@return the number of GUI ticks elapsed}
```

2023-07-16 20:49 UTC, Matyrobbrt commented on data/net/minecraft/client/gui/Gui.mapping
> +		COMMENT {@return the {@link SpectatorGui} instance.}
```suggestion
		COMMENT {@return the {@link SpectatorGui} instance}
```

2023-07-16 20:49 UTC, Matyrobbrt commented on data/net/minecraft/client/gui/Gui.mapping
> +		COMMENT {@return the {@link PlayerTabOverlay} overlay.}
```suggestion
		COMMENT {@return the {@link PlayerTabOverlay} overlay}
```

2023-07-16 20:49 UTC, Matyrobbrt commented on data/net/minecraft/client/gui/Gui.mapping
> +		COMMENT {@return {@code true} if the chat disabled message is being shown, {@code false} otherwise.}
```suggestion
		COMMENT {@return {@code true} if the chat disabled message is being shown, {@code false} otherwise}
```

2023-07-16 20:49 UTC, Matyrobbrt commented on data/net/minecraft/client/gui/components/events/ContainerEventHandler.mapping
> +		COMMENT {@return The current focus path as a ComponentPath, or {@code null} if there is no current focus path.}
```suggestion
		COMMENT {@return the current focus path as a ComponentPath, or {@code null}}
```

2023-07-16 20:49 UTC, Matyrobbrt commented on data/net/minecraft/client/gui/components/events/ContainerEventHandler.mapping
> +		COMMENT {@return {@code true} if the GUI element is focused, {@code false} otherwise.
```suggestion
		COMMENT {@return {@code true} if the GUI element is focused, {@code false} otherwise}
```

2023-07-16 20:49 UTC, Matyrobbrt commented on data/net/minecraft/client/gui/components/events/GuiEventListener.mapping
> +		COMMENT {@return the {@link ScreenRectangle} occupied by the GUI element.}
```suggestion
		COMMENT {@return the {@link ScreenRectangle} occupied by the GUI element}
```

2023-07-16 20:49 UTC, Matyrobbrt commented on data/net/minecraft/client/gui/components/events/GuiEventListener.mapping
> +		COMMENT {@return {@code true} if the GUI element is focused, {@code false} otherwise.
```suggestion
		COMMENT {@return {@code true} if the GUI element is focused, {@code false} otherwise}
```

2023-07-16 20:49 UTC, Matyrobbrt commented on data/net/minecraft/client/gui/components/tabs/TabNavigationBar.mapping
> +		COMMENT {@return the {@link ScreenRectangle} occupied by the GUI element.}
```suggestion
		COMMENT {@return the {@link ScreenRectangle} occupied by the GUI element}
```

2023-07-16 20:49 UTC, Matyrobbrt commented on data/net/minecraft/client/gui/components/tabs/TabNavigationBar.mapping
> +		COMMENT {@return the narration priority.}
```suggestion
		COMMENT {@return the narration priority}
```

2023-08-01 08:13 UTC, sciwhiz12 requested changes

2023-08-01 08:13 UTC, sciwhiz12 commented on data/net/minecraft/client/gui/ComponentPath.mapping
> +	COMMENT The {@code ComponentPath} interface represents a path of components in a user interface hierarchy.
No need to spell out the name of the class in its own javadoc.

```suggestion
	COMMENT Represents a path of components in a user interface hierarchy.
```

2023-08-01 08:13 UTC, sciwhiz12 commented on data/net/minecraft/client/gui/ComponentPath.mapping
> +		COMMENT Creates a component path with the specified {@code GuiEventListener} component and an array of {@code ContainerEventHandler} children.
This isn't exactly right.

The code tells us that the first component becomes the `Leaf` node, and then each `ContainerEventHandler` afterwards (if any) become the node's ancestors.

So to construct a path to some component with this method, you first pass in that target component, then its parent, then its grandparent, and so on.

To describe it in more symbolic language, given a hierarchy of `A -> B -> C`, constructing a path to component `C` would mean calling this method as `path(C, B, A)`.

2023-08-01 08:13 UTC, sciwhiz12 commented on data/net/minecraft/client/gui/Gui.mapping
> +			COMMENT the {@link HitResult} object representing the result of a ray trace operation.
This is also okay enough, but I would rather that this be simplified.
```suggestion
			COMMENT the result of a ray trace operation.
```

We usually neither need to say that a parameter is an object representing something (since that is usually the case, especially for a named class), nor do we need to note the type of the parameter in the javadoc (since where you can see the javadoc, you can also see the type).

2023-08-01 08:13 UTC, sciwhiz12 commented on data/net/minecraft/client/gui/Gui.mapping
> +		COMMENT Draws a backdrop with the provided GuiGraphics object, font, and dimensions, at the specified Y-position.
Specifically, this is a backdrop for text, which explains why we have to pass in a `Font` (it takes the line height of the font). Also, it seems that this is an odd one out among your additions to this class, with the use of `Y-position` versus the others' `y-coordinate`.
```suggestion
		COMMENT Draws a backdrop for text with the provided GuiGraphics object, font, and dimensions, at the specified y-coordinate.
```

2023-08-01 08:13 UTC, sciwhiz12 commented on data/net/minecraft/client/gui/Gui.mapping
>  		ARG 1 mountHealth
Should we rename the parameter to `vehicleHealth`, in line with the method name?

2023-08-01 08:13 UTC, sciwhiz12 commented on data/net/minecraft/client/gui/Gui.mapping
>  		ARG 1 mountEntity
Should we rename the parameter to `vehicle`, in line with the method name?

2023-08-01 08:13 UTC, sciwhiz12 commented on data/net/minecraft/client/gui/components/TabOrderedElement.mapping
> +	METHOD getTabOrderGroup ()I
Future work (not this PR specifically) should update this javadoc to clarify what the returned value means, specifically. (I.E. What does returning `2` mean? Is it context-specific? Does it follow an pattern like `0` before `1`? How about negatives?)

2023-08-01 08:13 UTC, sciwhiz12 commented on data/net/minecraft/client/gui/components/events/GuiEventListener.mapping
> +	COMMENT It extends the `TabOrderedElement` interface, providing tab order functionality for GUI components.
Simplification (to eliminate the redundancy of repeating the class name), paragraph tag addition, and Markdown monospace to `{@code}` javadoc tag conversion.
```suggestion
	COMMENT Represents a listener for GUI events.
	COMMENT <p>
	COMMENT It extends the {@code TabOrderedElement} interface, providing tab order functionality for GUI components.
```

2023-08-01 08:13 UTC, sciwhiz12 commented on data/net/minecraft/client/gui/components/events/GuiEventListener.mapping
> +		COMMENT @return the next focus path as a ComponentPath, or `null` if there is no next focus path.
```suggestion
		COMMENT @return the next focus path as a ComponentPath, or {@code null} if there is no next focus path.
```

2023-08-01 08:13 UTC, sciwhiz12 commented on data/net/minecraft/client/gui/components/tabs/TabNavigationBar.mapping
> +		COMMENT @return the next focus path as a ComponentPath, or `null` if there is no next focus path.
```suggestion
		COMMENT @return the next focus path as a ComponentPath, or {@code null} if there is no next focus path.
```

2023-08-01 08:13 UTC, sciwhiz12 commented on data/net/minecraft/client/gui/components/events/ContainerEventHandler.mapping
> +		COMMENT @return The next focus path as a ComponentPath, or `null` if there is no next focus path.
```suggestion
		COMMENT @return The next focus path as a ComponentPath, or {@code null} if there is no next focus path.
```

2023-08-01 08:13 UTC, sciwhiz12 commented on data/net/minecraft/client/gui/GuiGraphics.mapping
>  		ARG 4 width
Missed a parameter. 😄
```suggestion
		ARG 4 width
			COMMENT the width of the blitted portion.
```

2023-08-01 08:13 UTC, sciwhiz12 commented on data/net/minecraft/client/gui/GuiGraphics.mapping
> +			COMMENT the width and height of the blitted portion.
```suggestion
			COMMENT the width of the blitted portion.
```

2023-08-01 08:13 UTC, sciwhiz12 commented on data/net/minecraft/client/gui/GuiGraphics.mapping
> +			COMMENT the vertical texture coordinate offset.
Inconsistent?

2023-08-01 08:13 UTC, sciwhiz12 commented on data/net/minecraft/client/gui/GuiGraphics.mapping
> +		COMMENT Blits a nine-sliced portion of the texture specified by the atlas location onto the screen.
Future work: describe what a "nine-sliced portion" is.

2023-08-01 08:13 UTC, sciwhiz12 commented on data/net/minecraft/client/gui/GuiGraphics.mapping
> +			COMMENT the y-coordinate of the top-left corner of the source position.
Small inconsistency.

2023-08-01 08:13 UTC, sciwhiz12 commented on data/net/minecraft/client/gui/GuiGraphics.mapping
> +			COMMENT the first y-coordinate of the first corner of the rectangle.
Small inconsistency.

2023-08-01 08:13 UTC, sciwhiz12 commented on data/net/minecraft/client/gui/GuiGraphics.mapping
> +		COMMENT @deprecated This method is deprecated.
Future work: determining why these methods are deprecated.

2023-08-01 08:13 UTC, sciwhiz12 commented on data/net/minecraft/client/gui/GuiGraphics.mapping
> +		COMMENT {@return returns the PoseStack used for transformations and rendering.}
The word "Returns" and the final period should not be used for the inline `{@return}` tag, as the tag itself will insert them.
```suggestion
		COMMENT {@return the PoseStack used for transformations and rendering}
```

2023-08-01 08:44 UTC, Lanse505 commented on data/net/minecraft/client/gui/ComponentPath.mapping
> +		COMMENT Creates a component path with the specified {@code GuiEventListener} component and an array of {@code ContainerEventHandler} children.
This method only has 2 inputs, the last ComponentPath you're looking at is the return value.

The method looks like this:
```java
    /**
     * Creates a component path with the specified {@code ContainerEventHandler} component and an optional child path.
     * <p>
     * @return a new component path, or {@code null} if the child path is null
     * @param component the component associated with the path
     * @param childPath the child path associated with the component
     */
    @Nullable
    public static ComponentPath path(ContainerEventHandler component, @Nullable ComponentPath childPath) {
        if (childPath == null) {
            return null;
        }
        return new Path(component, childPath);
    }
```

2023-08-01 08:46 UTC, sciwhiz12 commented on data/net/minecraft/client/gui/ComponentPath.mapping
> +		COMMENT Creates a component path with the specified {@code GuiEventListener} component and an array of {@code ContainerEventHandler} children.
That's not the method I made my comment on; the one I made my comment on has a descriptor of `(Lnet/minecraft/client/gui/components/events/GuiEventListener;[Lnet/minecraft/client/gui/components/events/ContainerEventHandler;)Lnet/minecraft/client/gui/ComponentPath;`, which corresponds to the method `static ComponentPath path(GuiEventListener, ContainerEventHandler...)`.

2023-08-01 08:51 UTC, Lanse505 commented on data/net/minecraft/client/gui/ComponentPath.mapping
> +		COMMENT Creates a component path with the specified {@code GuiEventListener} component and an array of {@code ContainerEventHandler} children.
Ah missed the [] hooks in the description sorry.

Does this sound better?
```java
    /**
     * Creates a new {@code ComponentPath} leaf node with the specified {@code GuiEventListener} component and an array of {@code ContainerEventHandler} ancestors.
     * <p>
     * @return a new component path
     * @param leafComponent the new 'Leaf' component associated with the path
     * @param ancestorComponents the array of ancestor components associated with the path, ordered in reverse ascending order towards root.
     */
    public static ComponentPath path(GuiEventListener leafComponent, ContainerEventHandler ... ancestorComponents) {
        ComponentPath $$2 = ComponentPath.leaf(leafComponent);
        for (ContainerEventHandler $$3 : ancestorComponents) {
            $$2 = ComponentPath.path($$3, $$2);
        }
        return $$2;
    }
```

2023-08-01 09:26 UTC, sciwhiz12 commented on data/net/minecraft/client/gui/ComponentPath.mapping
> +		COMMENT Creates a component path with the specified {@code GuiEventListener} component and an array of {@code ContainerEventHandler} children.
Sounds fine to me, yep.

2023-08-01 09:52 UTC, sciwhiz12 approved these changes

2023-08-01 09:53 UTC, merged