Mappings for net/minecraft/world/level/chunk/storage
ParchmentMC/Parchment pull request #22
Opened 2021-06-25 18:54 UTC by noeppi-noeppi

2021-06-26 01:20 UTC, sciwhiz12 requested changes

2021-06-26 01:20 UTC, sciwhiz12 commented on data/net/minecraft/world/level/chunk/storage/EntityStorage.mapping
> +		ARG 5 executor
Something brought up in the mentioned PR is the (yet-to-be-fully-resolved) point of 'parameters follow field names': `executor` -> `mainThreadExecutor`.

2021-06-26 01:20 UTC, sciwhiz12 commented on data/net/minecraft/world/level/chunk/storage/RegionBitmap.mapping
> +		COMMENT Gets a valid offset inside the region file with wnough space to store the given amount of sectors and marks tha tspace as used.
Typos:
```suggestion
		COMMENT Gets a valid offset inside the region file with enough space to store the given amount of sectors and marks that space as used.
```

2021-06-26 01:20 UTC, sciwhiz12 commented on data/net/minecraft/world/level/chunk/storage/RegionFile.mapping
> +			ARG 2 chunkPos
Note the brought-up point of 'parameters follow field names': `chunkPos` -> `pos`.

2021-06-26 01:20 UTC, sciwhiz12 commented on data/net/minecraft/world/level/chunk/storage/RegionFileStorage.mapping
> +		ARG 1 regionFolder
Note the brought-up point of 'parameters follow field names': `regionFolder` -> `folder`.

2021-06-26 01:20 UTC, sciwhiz12 commented on data/net/minecraft/world/level/chunk/storage/RegionFileVersion.mapping
> +	COMMENT A decorator for input and output streams used to read and write the chunk data from region files..
The comment should also describe that the class represents the known versions (compression methods) of the region file format, possibly.

2021-06-26 01:21 UTC, sciwhiz12 commented
This may conflict with changes in #19 (depending on whichever may be merged in first).

2021-06-26 09:52 UTC, sciwhiz12 approved these changes

2021-06-28 02:53 UTC, jriwanek approved these changes

2021-06-30 03:58 UTC, merged