work on both commands packages
ParchmentMC/Parchment pull request #230
Opened 2023-07-29 00:30 UTC by Machine-Maker

2023-07-29 00:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/ParchmentMC/Parchment?pullRequest=230) <br/>All committers have signed the CLA.

2023-07-29 00:48 UTC, alcatrazEscapee requested changes
Overall looks good, a couple comments and one typo.

2023-07-29 00:48 UTC, alcatrazEscapee commented on data/net/minecraft/commands/arguments/ArgumentSignatures.mapping
> +		ARG 0 byteBuf
```suggestion
		ARG 0 buffer
```

As per previously established conventions, [here](https://github.com/ParchmentMC/Parchment/pull/207#discussion_r1248014538), and [here](https://github.com/ParchmentMC/Parchment/pull/24#pullrequestreview-695217286)

2023-07-29 00:48 UTC, alcatrazEscapee commented on data/net/minecraft/server/commands/ResetChunksCommand.mapping
> +		ARG 0 soruce
```suggestion
		ARG 0 source
```

2023-07-29 00:48 UTC, alcatrazEscapee commented on data/net/minecraft/commands/arguments/GameModeArgument.mapping
> +		ARG 0 unknownGameType
```suggestion
		ARG 0 invalidGameType
```

Based on the field `ERROR_INVALID` and translation `"argument.gamemode.invalid"` using `invalid`, not `unknown`.

2023-07-29 00:48 UTC, alcatrazEscapee commented on data/net/minecraft/server/commands/ScheduleCommand.mapping
> +		ARG 7 functionCollection
```suggestion
		ARG 7 functions
```

imo `functionCollection` is ungangly, this describes what it is better (either a single function, or functions plural). The type in question is the right of a `Either<CommandFunction, Collection<CommandFunction>>>`

2023-07-29 04:08 UTC, Machine-Maker commented
Ok, both commands packages should be completely done now except for methods that override things, like ArgumentType from brig.

2023-07-30 18:24 UTC, alcatrazEscapee requested changes

2023-07-30 18:24 UTC, alcatrazEscapee commented on data/net/minecraft/server/commands/EnchantCommand.mapping
> +		ARG 1 maxLvl
```suggestion
		ARG 0 requestedLevel
		ARG 1 maxLevel
```
Don't worry we can afford to pay extra for the vowels here.

2023-07-30 18:24 UTC, alcatrazEscapee commented on data/net/minecraft/server/commands/ExecuteCommand.mapping
> +		ARG 3 argBuilder
```suggestion
		ARG 3 builder
```

Would prefer `argumentBuilder` or `builder` over the not-a-full-word

2023-07-30 18:24 UTC, alcatrazEscapee commented on data/net/minecraft/server/commands/ExperienceCommand.mapping
> +			ARG 1 xp
```suggestion
			ARG 1 experiencePoints
```

2023-07-30 18:24 UTC, alcatrazEscapee commented on data/net/minecraft/server/commands/ExperienceCommand.mapping
> +			ARG 1 xp
```suggestion
			ARG 1 experienceLevels
```

Unless I'm mistaken, these two lambdas are referring to different values (as per `Type`) and this is a clearer name for each.

2023-07-30 18:24 UTC, alcatrazEscapee commented on data/net/minecraft/server/commands/JfrCommand.mapping
> +		ARG 0 msg
```suggestion
		ARG 0 message
```

2023-07-30 18:24 UTC, alcatrazEscapee commented on data/net/minecraft/server/commands/LootCommand.mapping
> +		ARG 1 argBuilder
```suggestion
		ARG 1 builder
```

2023-07-30 18:24 UTC, alcatrazEscapee commented on data/net/minecraft/server/commands/LootCommand.mapping
> +			ARG 1 argBuilder
```suggestion
			ARG 1 builder
```

2023-07-30 18:24 UTC, alcatrazEscapee commented on data/net/minecraft/server/commands/TeleportCommand.mapping
> +		ARG 0 soruce
```suggestion
		ARG 0 source
```

2023-07-30 18:24 UTC, alcatrazEscapee commented on data/net/minecraft/server/commands/data/BlockDataAccessor.mapping
> +		ARG 0 argName
```suggestion
		ARG 0 name
```

2023-07-30 18:24 UTC, alcatrazEscapee commented on data/net/minecraft/server/commands/data/DataCommands.mapping
> +		ARG 0 str
I don't like `str` as a arbitrary parameter name, it tells very little (other than the type, badly), and is a abbreviation. For all the similarly named parameters in this class.

2023-08-03 18:21 UTC, alcatrazEscapee approved these changes

2023-08-03 18:21 UTC, merged