Mappings for net/minecraft/world/level/levelgen
ParchmentMC/Parchment pull request #241
Opened 2023-08-03 00:52 UTC by PiTheGuy

2023-08-03 08:26 UTC, Lanse505 requested changes, later dismissed

2023-08-03 08:26 UTC, Lanse505 commented on data/net/minecraft/world/level/levelgen/structure/structures/WoodlandMansionPieces.mapping
> +			ARG 2 y
ARG 3 expectedValue

2023-08-03 18:08 UTC, alcatrazEscapee requested changes

2023-08-03 18:08 UTC, alcatrazEscapee commented on data/net/minecraft/world/level/levelgen/feature/rootplacers/RootPlacer.mapping
> +		ARG 0 codecBuilder
```suggestion
		ARG 0 instance
```

N.B. A brief [search](https://github.com/search?q=repo%3AParchmentMC%2FParchment%20RecordCodecBuilder%24Instance&type=code) shows we name this all sorts of things (most commonly `instance`, but also `in`, `locations`, `codec` among others), I think `instance` is the best + most commonly accepted name for this particular pattern.

2023-08-03 18:08 UTC, alcatrazEscapee commented on data/net/minecraft/world/level/levelgen/feature/stateproviders/NoiseBasedStateProvider.mapping
> +		ARG 0 codecBuilder
```suggestion
		ARG 0 instance
```

2023-08-03 18:08 UTC, alcatrazEscapee commented on data/net/minecraft/world/level/levelgen/feature/stateproviders/NoiseProvider.mapping
> +		ARG 0 codecBuilder
```suggestion
		ARG 0 instance
```

2023-08-03 18:08 UTC, alcatrazEscapee commented on data/net/minecraft/world/level/levelgen/structure/Structure.mapping
>  		ARG 0 codecBuilder
```suggestion
		ARG 0 instance
```

2023-08-03 18:08 UTC, alcatrazEscapee commented on data/net/minecraft/world/level/levelgen/structure/placement/ConcentricRingsStructurePlacement.mapping
> +		ARG 0 codecBuilder
```suggestion
		ARG 0 instance
```

2023-08-03 18:08 UTC, alcatrazEscapee commented on data/net/minecraft/world/level/levelgen/structure/placement/StructurePlacement.mapping
> +		ARG 0 codecBuilder
```suggestion
		ARG 0 instance
```

2023-08-06 15:20 UTC, alcatrazEscapee approved these changes

2023-08-06 15:21 UTC, merged