mapped a lot of net/minecraft/client/screen/inventory
ParchmentMC/Parchment pull request #25
Opened 2021-06-25 21:35 UTC by agnor99

mapped also some other stuff I tumbled into

2021-06-26 07:43 UTC, Darkhax commented on data/net/minecraft/client/gui/screens/inventory/CreativeModeInventoryScreen.mapping
> +			COMMENT the list of items in this container
This should start with an upper case and end with a period.

2021-06-26 07:43 UTC, Darkhax commented on data/net/minecraft/client/gui/screens/inventory/CreativeModeInventoryScreen.mapping
> +			COMMENT Returns true if the player can "drag-spilt" items into this slot,. returns true by default. Called to check if the slot can be added to a list of Slots to split the held ItemStack across.
The `,` is not needed. The second returns should also be capitalized.

2021-06-26 14:21 UTC, diesieben07 requested changes

2021-06-26 14:21 UTC, diesieben07 commented on data/net/minecraft/client/gui/screens/inventory/CreativeModeInventoryScreen.mapping
> +			COMMENT Updates the gui slots ItemStack's based on scroll position.
Should be `slot's ItemStacks`

2021-06-26 14:21 UTC, diesieben07 commented on data/net/minecraft/world/inventory/AbstractContainerMenu.mapping
> +		ARG 2 containerID
The field is called `containerId`, we should mimic that.

2021-06-26 14:43 UTC, diesieben07 approved these changes, later dismissed

2021-06-26 20:39 UTC, Darkhax submitted a review, later dismissed

2021-06-28 02:56 UTC, jriwanek submitted a review, later dismissed

2021-06-28 13:46 UTC, Lanse505 requested changes

2021-06-28 13:46 UTC, Lanse505 commented on data/net/minecraft/client/gui/GuiComponent.mapping
> +		ARG 0 poseStack
Correct, but please update the rest of the class to fix this as well.
There are still a lot of "matrixPos" entries in there that needs to be renamed.

2021-06-28 13:46 UTC, Lanse505 commented on data/net/minecraft/client/gui/screens/inventory/AbstractContainerScreen.mapping
>  		ARG 1 matrixStack
``matrixStack`` -> ``poseStack``

Apply this change to any other instances you find.

2021-06-28 13:46 UTC, Lanse505 commented on data/net/minecraft/world/entity/player/Player.mapping
> +		ARG 1 signBlock
``signBlock`` -> ``signEntity``

2021-06-28 13:46 UTC, Lanse505 commented on data/net/minecraft/world/entity/player/Player.mapping
> +		ARG 1 structureBlock
``structureBlock`` -> ``structureEntity``

2021-06-28 13:46 UTC, Lanse505 commented on data/net/minecraft/world/entity/player/Player.mapping
> +		ARG 1 jigsawBlock
``jigsawBlock`` -> ``jigsawEntity``

2021-06-28 13:46 UTC, Lanse505 commented on data/net/minecraft/world/inventory/tooltip/BundleTooltip.mapping
> +		ARG 1 itemStacks
``itemStacks`` -> ``items``

2021-06-28 17:42 UTC, Lanse505 approved these changes

2021-06-28 17:52 UTC, jriwanek approved these changes

2021-06-28 23:35 UTC, Darkhax approved these changes

2021-06-29 12:20 UTC, OrionDevelopment approved these changes

2021-06-30 16:59 UTC, merged