Update to 1.20.2
ParchmentMC/Parchment pull request #259
Opened 2023-09-21 17:47 UTC by PiTheGuy

JAMMER didn't seem to help that much in terms of file count...

2023-09-21 18:40 UTC, sciwhiz12 commented
oh lawd

2023-09-21 18:42 UTC, Matyrobbrt commented
Oh, lovely, this will be fun

2023-09-21 19:02 UTC, Lanse505 commented
I demand a raise >.>

2023-10-02 09:04 UTC, sciwhiz12 requested changes
Skimmed the PR, mostly looking for typos and obvious errors.

Didn't go too indepth with comparing between the code and the names, so there _might_ be some things that'll slip by us. I don't think that'll be too much of an issue.

I am now contemplating making a script which collects all of the parameter names and does word-comparisons to find likely typos; as in, check how similar two words are, and log if they're very similar and the change isn't something like an `s` appended to the end. Probably will be an external script, not included in this repo (unless I think it's good enough to be included).

2023-10-02 09:04 UTC, sciwhiz12 commented on data/net/minecraft/commands/CommandSourceStack.mapping
> +		ARG 2 chatMessageContainer
This should be `chatMessageChainer`.

```suggestion
		ARG 2 chatMessageChainer
```

2023-10-02 09:04 UTC, sciwhiz12 commented on data/net/minecraft/advancements/critereon/EntityEquipmentPredicate.mapping
> +			ARG 1 offfhand
Typo: `offfhand` to `offhand`.
```suggestion
			ARG 1 offhand
```

2023-10-02 09:04 UTC, sciwhiz12 commented on data/net/minecraft/advancements/critereon/RecipeCraftedTrigger.mapping
> +			ARG 2 recipedId
Typo: `recipedId` to `recipeId`.
```suggestion
			ARG 2 recipeId
```

2023-10-02 09:04 UTC, sciwhiz12 commented on data/net/minecraft/client/multiplayer/ClientCommonPacketListenerImpl.mapping
> +		ARG 1 resoursePackUrl
Typo: `resoursePackUrl` to `resourcePackUrl`.

```suggestion
		ARG 1 resourcePackUrl
```

2023-10-02 09:04 UTC, sciwhiz12 commented on data/net/minecraft/world/effect/MobEffect.mapping
> +		ARG 1 attrubuteMap
Typo: `attrubuteMap` to `attributeMap`.

```suggestion
		ARG 1 attributeMap
```

2023-10-02 09:04 UTC, sciwhiz12 commented on data/net/minecraft/world/level/storage/loot/predicates/WeatherCheck.mapping
> +			ARG 1 isThudering
Typo: `isThudering` to `isThundering`.

```suggestion
			ARG 1 isThundering
```

2023-10-02 09:04 UTC, sciwhiz12 commented on data/net/minecraft/world/level/storage/loot/entries/LootTableReference.mapping
> +		ARG 4 coditions
Typo: `coditions` to `conditions`.

```suggestion
		ARG 4 conditions
```

2023-10-04 04:35 UTC, sciwhiz12 approved these changes

2023-10-04 04:39 UTC, merged