Finish Parameter Mappings for `net.minecraft.client.gui`
ParchmentMC/Parchment pull request #260
Opened 2023-10-07 20:21 UTC by ChampionAsh5357

Adds the rest of the missing parameters for `net.minecraft.client.gui`. Lambdas are not included since I don't remember whether those are allowed :p.

2023-10-07 22:04 UTC, alcatrazEscapee commented
Lambdas are allowed, yes, and encouraged, because other people not using Forge exist and can benefit from said mappings.

2023-10-12 05:56 UTC, Matyrobbrt requested changes

2023-10-12 05:56 UTC, Matyrobbrt commented on data/net/minecraft/client/gui/screens/worldselection/CreateWorldScreen.mapping
> +		ARG 2 registries
```suggestion
		ARG 2 registryAccess
```

2023-10-12 05:56 UTC, Matyrobbrt commented on data/net/minecraft/client/gui/screens/recipebook/OverlayRecipeComponent.mapping
> +		ARG 5 copmonentXCenter
```suggestion
		ARG 5 componentXCenter
```

2024-04-10 09:39 UTC, sciwhiz12 commented
Due to the length of time and versions past since this was opened, I'm going to close this PR as stale. If you want to continue this PR, be my guest and reopen the PR. Thanks!

2024-04-10 09:39 UTC, closed without merging