Parameter names and Javadocs for the Loot system
ParchmentMC/Parchment pull request #29
Opened 2021-06-26 13:24 UTC by diesieben07

2021-06-28 03:03 UTC, jriwanek submitted a review, later dismissed

2021-06-28 10:59 UTC, Lanse505 requested changes
Looked good overall.

I've left a few comments that needs to be adressed in theory.
Also there is something wierd with your patch where in some mapping classes contains double class headers, I've tagged @sciwhiz12 about this so he can look into it.

Otherwise great work Dies!

2021-06-28 10:59 UTC, Lanse505 commented on data/net/minecraft/world/level/storage/loot/BuiltInLootTables.mapping
> +CLASS net/minecraft/world/level/storage/loot/BuiltInLootTables net/minecraft/world/level/storage/loot/BuiltInLootTables
Why the double identifier...? @sciwhiz12

2021-06-28 10:59 UTC, Lanse505 commented on data/net/minecraft/world/level/storage/loot/GsonAdapterFactory.mapping
> +			ARG 4 function
``function`` -> ``typeGetter``

2021-06-28 10:59 UTC, Lanse505 commented on data/net/minecraft/world/level/storage/loot/LootContext.mapping
> +			ARG 3 random
``random`` -> ``seed``

2021-06-28 10:59 UTC, Lanse505 commented on data/net/minecraft/world/level/storage/loot/entries/EntryGroup.mapping
> +CLASS net/minecraft/world/level/storage/loot/entries/EntryGroup net/minecraft/world/level/storage/loot/entries/EntryGroup
Same as before, double indentifiers >.> @sciwhiz12

2021-06-28 10:59 UTC, Lanse505 commented on data/net/minecraft/world/level/storage/loot/entries/LootItem.mapping
> +CLASS net/minecraft/world/level/storage/loot/entries/LootItem net/minecraft/world/level/storage/loot/entries/LootItem
Same as before, double indentifiers >.> @sciwhiz12

2021-06-29 04:34 UTC, Darkhax requested changes
Looks good to me, approval pending the double header issue.

2021-06-29 12:24 UTC, Lanse505 approved these changes

2021-06-29 12:24 UTC, Lanse505 commented
@Darkhax feel free to approve, double headers is not a bug.

2021-07-01 13:35 UTC, Lanse505 approved these changes

2021-07-01 22:38 UTC, Darkhax approved these changes

2021-07-04 10:32 UTC, merged