Some misc mappings
ParchmentMC/Parchment pull request #30
Opened 2021-06-26 18:27 UTC by ravenbuilder934

- `net.minecraft.world.damagesource`
 - `net.minecraft.world.effect`
 - `net.minecraft.world.food`
 - `net.minecraft.world.scores`

2021-06-28 03:05 UTC, jriwanek submitted a review, later dismissed

2021-06-28 09:57 UTC, Lanse505 requested changes

2021-06-28 09:57 UTC, Lanse505 commented on data/net/minecraft/stats/ServerStatsCounter.mapping
> +		ARG 0 tag
``tag`` -> ``tagObject``

2021-06-28 09:57 UTC, Lanse505 commented on data/net/minecraft/stats/ServerStatsCounter.mapping
> +		ARG 1 map
``map`` -> ``type``

2021-06-28 09:57 UTC, Lanse505 commented on data/net/minecraft/stats/ServerStatsCounter.mapping
> +		ARG 2 json
``json`` -> ``id``

2021-06-28 09:57 UTC, Lanse505 commented on data/net/minecraft/stats/ServerStatsCounter.mapping
> +		ARG 0 json
``json`` -> ``type``

It's returning the type object there not a json object.

2021-06-28 09:57 UTC, Lanse505 commented on data/net/minecraft/stats/Stat.mapping
> +		ARG 1 object
``object`` -> ``other``

2021-06-28 09:57 UTC, Lanse505 commented on data/net/minecraft/stats/StatsCounter.mapping
> +		ARG 2 item
``item`` -> ``type``

2021-06-28 09:57 UTC, Lanse505 commented on data/net/minecraft/world/damagesource/BadRespawnPointDamage.mapping
> +		ARG 0 modifyFunc
``modifyFunc`` -> ``componentStyle``

2021-06-28 09:57 UTC, Lanse505 commented on data/net/minecraft/world/damagesource/EntityDamageSource.mapping
> +		ARG 1 damageType
``damageType`` -> ``damageTypeId``

2021-06-28 09:57 UTC, Lanse505 commented on data/net/minecraft/world/damagesource/IndirectEntityDamageSource.mapping
> +		ARG 1 damageType
``damageType`` -> ``damageTypeId``

2021-06-28 09:57 UTC, Lanse505 commented on data/net/minecraft/world/effect/AttackDamageMobEffect.mapping
> +		ARG 1 type
``type`` -> ``category``

2021-06-28 09:57 UTC, Lanse505 commented on data/net/minecraft/world/effect/MobEffectInstance.mapping
> +		ARG 1 mobEffect
``mobEffect`` -> ``effectInstance``

2021-06-28 09:57 UTC, Lanse505 commented on data/net/minecraft/world/effect/MobEffectInstance.mapping
> +		ARG 1 hashCode
``hashCode`` -> ``other``

2021-06-28 09:57 UTC, Lanse505 commented on data/net/minecraft/world/effect/MobEffectInstance.mapping
> +		ARG 1 mobEffect
``mobEffect`` -> ``effectInstance``

2021-06-28 09:57 UTC, Lanse505 commented on data/net/minecraft/world/effect/MobEffectInstance.mapping
> +		ARG 2 runnable
``runnable`` -> ``onExpirationRunnable``

2021-06-28 09:57 UTC, Lanse505 commented on data/net/minecraft/world/scores/Objective.mapping
> +		ARG 1 modifyFunc
``modifyFunc`` -> ``style``

2021-07-12 16:05 UTC, Lanse505 approved these changes

2021-07-12 19:29 UTC, jriwanek approved these changes

2021-07-14 20:34 UTC, merged