Maps net.minecraft.world.item and some subfolders
ParchmentMC/Parchment pull request #32
Opened 2021-06-26 23:27 UTC by ravenbuilder934

- `net.minecraft.world.item` base folder
- `net.minecraft.world.item.context`
- `net.minecraft.world.item.crafting`
- `net.minecraft.world.item.trading`
Not quite finished, still a draft.

2021-07-07 07:57 UTC, mcenderdragon commented on data/net/minecraft/world/item/CrossbowItem.mapping
> +		ARG 0 flag
what flag exactly?

2021-07-07 07:57 UTC, mcenderdragon commented on data/net/minecraft/world/item/BucketItem.mapping
> +		ARG 1 content
so far every param was similar to the class tpye, maybe fluid instead of content?

2021-07-07 07:57 UTC, mcenderdragon commented on data/net/minecraft/world/item/FireworkRocketItem.mapping
> +			ARG 4 name
is this a real name or a langKey ?

2021-07-07 07:57 UTC, mcenderdragon commented on data/net/minecraft/world/item/ItemStack.mapping
> +		ARG 0 hideFlags
maybe add a javadoc to explain these hideFlags in more detail?

2021-07-14 20:16 UTC, alcatrazEscapee requested changes
Some misc. ramblings

2021-07-14 20:16 UTC, alcatrazEscapee commented on data/net/minecraft/world/item/ArmorItem.mapping
> +		ARG 1 itemStack
I'd be tempted to call these both `source` / and `stack` or `item`, depending on other context. Not sure if it's nessecary.

2021-07-14 20:16 UTC, alcatrazEscapee commented on data/net/minecraft/world/item/ItemStack.mapping
> +		ARG 1 blockB
Maybe `first` and `second`?

2021-07-14 20:16 UTC, alcatrazEscapee commented on data/net/minecraft/world/item/ItemStack.mapping
> +		ARG 2 cachedPlaceBlock
The `cached` arguments don't sound grammatically correct - is it the cached block about to be broken / placed? Then it might be `cachedBlockToBreak` or `cachedBlockToPlace`

2021-07-14 20:16 UTC, alcatrazEscapee commented on data/net/minecraft/world/item/ProjectileWeaponItem.mapping
> +		ARG 0 entityLiving
`livingEntity`

2021-07-14 20:16 UTC, alcatrazEscapee commented on data/net/minecraft/world/item/ShearsItem.mapping
> +		ARG 0 entityLiving
`livingEntity`

2021-07-14 20:16 UTC, alcatrazEscapee commented on data/net/minecraft/world/item/SpawnEggItem.mapping
> +		ARG 3 color2
`primaryColor` / `secondaryColor`? or `main` / `accent`? Again the suffixes don't really tell you anything here

2021-07-14 20:16 UTC, alcatrazEscapee commented on data/net/minecraft/world/item/TridentItem.mapping
> +		ARG 1 entityLiving
`livingEntity` here, twice

2021-07-14 20:16 UTC, alcatrazEscapee commented on data/net/minecraft/world/item/context/BlockPlaceContext.mapping
> +		ARG 1 blockPos
`pos`

2021-07-14 20:16 UTC, alcatrazEscapee commented on data/net/minecraft/world/item/context/DirectionalPlaceContext.mapping
> +		ARG 4 itemStack
`stack` and `pos` here too. `direction` and `directionAgainst` I'm not sold on, that doesn't really sound like enough to know what they're doing. (I know the former is a field name).

2021-07-14 20:16 UTC, alcatrazEscapee commented on data/net/minecraft/world/item/crafting/ShapedRecipe.mapping
> +		ARG 0 object
`json`

2022-03-05 10:22 UTC, sciwhiz12 commented
Hello! 👋 It has been a good amount of time since this PR was last reviewed, and none of the changes requested by the reviewers have been addressed. Because of this, we will assume (unless told otherwise) that this PR has been abandoned, and will therefore close it as such. 

If you wish to resolve the requested changes and continue this PR, please leave a comment saying so and we will reopen the PR. Thank you for your contributions!

2022-03-05 10:22 UTC, closed without merging