Project Phoenix: `net.minecraft.world.level.block` and children
ParchmentMC/Parchment pull request #41
Opened 2021-07-06 17:59 UTC by diesieben07

Only obvious things are named / corrected from MCP. No new Javadoc except small changes from MCP for names/wording.
If something is wrong but unclear, I've simply removed it, it will be added back later.

I have also removed any copied Javadoc from overridden methods so that IDEs can simply display the inherited one, instead of us having to maintain the copy-pasted version.

2021-07-06 18:16 UTC, sciwhiz12 submitted a review, later dismissed
Please remove the following methods for the automatic data validation task to pass.

To my understanding, somehow Enigma is mapping the synthetic bouner counterpart of the method instead of the actual method (as evidenced by the descriptor referencing `java/lang/Object`). 

I am working on finding the cause and fixing it, but for now to fix it either manually remove the methods from the files or run in order the following tasks: `createStagingFromInputs sanitizeStagingData promoteStangingToProduction` (or more succintly, `cSFI ssD pSTP` on the command line).

2021-07-06 18:16 UTC, sciwhiz12 commented on data/net/minecraft/world/level/block/state/predicate/BlockMaterialPredicate.mapping
> +		ARG 1 state
Please remove this method.

2021-07-06 18:16 UTC, sciwhiz12 commented on data/net/minecraft/world/level/block/state/predicate/BlockPredicate.mapping
> +		ARG 1 state
Please remove this method.

2021-07-06 18:16 UTC, sciwhiz12 commented on data/net/minecraft/world/level/block/state/predicate/BlockStatePredicate.mapping
> +		ARG 1 state
Please remove this method.

2021-07-14 20:12 UTC, alcatrazEscapee requested changes

2021-07-14 20:12 UTC, alcatrazEscapee commented on data/net/minecraft/world/level/block/KelpBlock.mapping
> +		ARG 1 rand
`random`

2021-07-14 20:12 UTC, alcatrazEscapee commented on data/net/minecraft/world/level/block/SoulSandBlock.mapping
>  		ARG 4 rand
`random`

2021-07-14 20:12 UTC, alcatrazEscapee commented on data/net/minecraft/world/level/block/SugarCaneBlock.mapping
>  		ARG 4 rand
`random`

2021-07-14 20:12 UTC, alcatrazEscapee commented on data/net/minecraft/world/level/block/VineBlock.mapping
>  		ARG 2 rot
`rotation`

2021-07-14 20:12 UTC, alcatrazEscapee commented on data/net/minecraft/world/level/block/WallBlock.mapping
>  		ARG 2 rot
`rotation`

2021-07-14 20:12 UTC, alcatrazEscapee commented on data/net/minecraft/world/level/block/grower/SpruceTreeGrower.mapping
>  		ARG 1 rand
`random`

2021-07-14 20:12 UTC, alcatrazEscapee commented on data/net/minecraft/world/level/block/state/BlockBehaviour.mapping
> +		ARG 2 rot
`rotation`

2021-07-14 20:12 UTC, alcatrazEscapee commented on data/net/minecraft/world/level/block/state/BlockBehaviour.mapping
>  			ARG 1 reader
`level`

2021-07-14 23:09 UTC, alcatrazEscapee approved these changes

2021-07-23 14:30 UTC, Lanse505 approved these changes

2021-07-23 14:31 UTC, Lanse505 commented
Looks good to me, also jfc that's a lot of files to go through 😓

2021-07-25 15:23 UTC, merged