Add/Update some mappings for `net.minecraft.client.model.*`.
ParchmentMC/Parchment pull request #49
Opened 2021-07-24 21:17 UTC by iChun

2021-07-24 21:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ParchmentMC/Parchment?pullRequest=49) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ParchmentMC/Parchment?pullRequest=49) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ParchmentMC/Parchment?pullRequest=49) it.</sub>

2021-07-24 21:18 UTC, Lanse505 commented
Sorry we don't accept PRs from Ichun ;P 
(Btw sign the CLA)

2021-07-24 21:22 UTC, iChun commented
> Sorry we don't accept PRs from Ichun ;P
> (Btw sign the CLA)

https://i.pinimg.com/474x/a0/1f/aa/a01faaf76ffe1ae9a0eeac3dfd1a44e0.jpg

2021-07-26 14:57 UTC, WithoutAName25 requested changes
Some small suggestions

2021-07-26 14:57 UTC, WithoutAName25 commented on data/net/minecraft/client/model/geom/ModelPart.mapping
> +		ARG 1 x
Maybe take field names instead
```suggestion
		ARG 1 xRot
```

2021-07-26 14:57 UTC, WithoutAName25 commented on data/net/minecraft/client/model/geom/ModelPart.mapping
> +		ARG 2 y
```suggestion
		ARG 2 yRot
```

2021-07-26 14:57 UTC, WithoutAName25 commented on data/net/minecraft/client/model/geom/ModelPart.mapping
> +		ARG 3 z
```suggestion
		ARG 3 zRot
```

2021-07-26 14:57 UTC, WithoutAName25 commented on data/net/minecraft/client/model/geom/builders/CubeDefinition.mapping
> +		ARG 2 texCoordX
```suggestion
		ARG 2 texCoordU
```

2021-07-26 14:57 UTC, WithoutAName25 commented on data/net/minecraft/client/model/geom/builders/CubeDefinition.mapping
> +		ARG 3 texCoordY
```suggestion
		ARG 3 texCoordV
```

2021-07-30 04:09 UTC, iChun commented
@WithoutAName25 done

2021-07-30 08:52 UTC, WithoutAName25 submitted a review, later dismissed

2021-07-30 11:18 UTC, sciwhiz12 requested changes
A small thing that needs changing, otherwise it's all fine to me.

2021-07-30 11:18 UTC, sciwhiz12 commented on data/net/minecraft/client/model/geom/builders/CubeDefinition.mapping
> +		ARG 10 cubeDeformation
According to convention, this should follow the name of the field which the parameter is directly assigned to: `grow`.

2021-08-01 10:45 UTC, iChun commented
@sciwhiz12 Done.

Let me know if you'd like me to squash the commits as well

2021-08-01 11:50 UTC, WithoutAName25 approved these changes

2021-08-01 13:25 UTC, sciwhiz12 approved these changes
Looks good to me. No need to squash the commits on your end, standard procedure is to squash-merge PRs from GitHub.

2021-08-03 13:52 UTC, merged