Mappings for `net.minecraft.stats`.
ParchmentMC/Parchment pull request #65
Opened 2021-08-13 19:07 UTC by Harleyoc1

Mapped (and updated) all parameters in `net.minecraft.stats`. Also added some Javadoc to stat-related classes (honestly no idea why recipe book classes are in this package).

2021-08-14 03:40 UTC, alcatrazEscapee requested changes
Mostly just inconsistient use of newlines. In short:

- Don't insert line breaks (new `COMMENT` lines) manually for overlong lines (although do so if you want the comment itself to break a line.
- Use `<p>` for empty lines if you want an explicit newline, or don't (your choice). Don't mix and match styles, especially within the same comment.

2021-08-14 03:40 UTC, alcatrazEscapee commented on data/net/minecraft/stats/ServerStatsCounter.mapping
> +	COMMENT {@linkplain net.minecraft.network.protocol.game.ClientboundAwardStatsPacket award stats packet}.
Comment should be one line.

2021-08-14 03:40 UTC, alcatrazEscapee commented on data/net/minecraft/stats/Stat.mapping
> +	COMMENT @see net.minecraft.stats.Stats
Incorrect newlines. Don't break in the middle of a sentence. Either use `<p>` on empty lines or don't, don't mix styles.

2021-08-14 03:40 UTC, alcatrazEscapee commented on data/net/minecraft/stats/Stat.mapping
> +		COMMENT type path>:<value namespace>.<value path>}
Comment should be on one line.

2021-08-14 03:40 UTC, alcatrazEscapee commented on data/net/minecraft/stats/StatFormatter.mapping
> +	COMMENT {@link #format(int)}.
Unnecessary comment. This is explaining expected knowledge. (The last two lines specifically)

2021-08-14 03:40 UTC, alcatrazEscapee commented on data/net/minecraft/stats/StatType.mapping
> +	COMMENT @see net.minecraft.core.Registry#CUSTOM_STAT
Incorrect usage of newlines in comments.

2021-08-14 03:40 UTC, alcatrazEscapee commented on data/net/minecraft/stats/StatsCounter.mapping
> +	COMMENT @see net.minecraft.stats.ServerStatsCounter
Incorrect usage of newlines in comments.

2021-08-14 15:51 UTC, alcatrazEscapee approved these changes

2021-08-21 19:04 UTC, Lanse505 approved these changes

2021-08-24 22:46 UTC, merged