Fix invalid parameter mappings
ParchmentMC/Parchment pull request #67
Opened 2021-08-26 03:04 UTC by SizableShrimp

This PR fixes some invalid parameters, mainly parameters that got missed either as old data from MCP or methods made static/non-static in the update of Parchment to 1.17.

This PR had `sanitizeData` run on it using a local build of Compass with [this commit](https://github.com/SizableShrimp/Compass/commit/14f8f40576446e3ecd015dfd5b7a15698f983e6d) to catch all the invalid parameters. Some synthetic data got removed automatically as well.

2021-08-26 15:45 UTC, Harleyoc1 requested changes

2021-08-26 15:45 UTC, Harleyoc1 commented on data/net/minecraft/advancements/AdvancementProgress.mapping
> -			ARG 3 context
This could be made valid instead of just removing it: 

```
	CLASS Serializer
		METHOD deserialize (Lcom/google/gson/JsonElement;Ljava/lang/reflect/Type;Lcom/google/gson/JsonDeserializationContext;)Lnet/minecraft/advancements/AdvancementProgress;
			ARG 1 json
			ARG 2 typeOfT
			ARG 3 context
		METHOD serialize (Lnet/minecraft/advancements/AdvancementProgress;Ljava/lang/reflect/Type;Lcom/google/gson/JsonSerializationContext;)Lcom/google/gson/JsonElement;
			ARG 1 src
			ARG 2 typeOfSrc
			ARG 3 context
```

2021-08-26 15:47 UTC, Lanse505 commented on data/net/minecraft/advancements/AdvancementProgress.mapping
> -			ARG 3 context
I think those might have been removed due to enigma cleaning them up, not him removing them.
@SizableShrimp can probably confirm this

2021-08-26 15:51 UTC, Harleyoc1 commented on data/net/minecraft/advancements/AdvancementProgress.mapping
> -			ARG 3 context
Probably, I'm just suggesting this as I had already written out the fix. The reason they were removed is that they are synthetic due to generics, so it makes sense to keep the corrected mappings.

2021-08-26 19:30 UTC, SizableShrimp commented on data/net/minecraft/advancements/AdvancementProgress.mapping
> -			ARG 3 context
There is no need to keep them. They should be cascaded in the exports.

2021-08-26 19:34 UTC, Harleyoc1 commented on data/net/minecraft/advancements/AdvancementProgress.mapping
> -			ARG 3 context
Ah OK. So it automatically populates this data from dependencies on export?

2021-08-26 19:36 UTC, SizableShrimp commented on data/net/minecraft/advancements/AdvancementProgress.mapping
> -			ARG 3 context
Oh dependencies? Actually I doubt it. I forgot these were from gson and not a parameter mapped inside of the minecraft codebase. Then we should probably keep it but the issue is every time sanitizeData is run this will get deleted and we have to undo it each time.

2021-08-26 19:38 UTC, Harleyoc1 commented on data/net/minecraft/advancements/AdvancementProgress.mapping
> -			ARG 3 context
sanitizeData shouldn't delete it once the actual method is mapped, it's just because the synthetic version (with `Ljava/lang/Object` rather than `Lnet/minecraft/advancements/AdvancementProgress`) was left in.

2021-08-26 19:40 UTC, Harleyoc1 commented on data/net/minecraft/advancements/AdvancementProgress.mapping
> -			ARG 3 context
That's what the code block above is for; maybe I didn't make it clear enough. Should work once that is pasted in as I copied the descriptor from the bytecode.

2021-08-26 19:41 UTC, SizableShrimp commented on data/net/minecraft/advancements/AdvancementProgress.mapping
> -			ARG 3 context
Ahh okay will fix 👍

2021-10-04 01:06 UTC, SizableShrimp commented on data/net/minecraft/advancements/AdvancementProgress.mapping
> -			ARG 3 context
Took me a while to get back around to it, but this is now fixed.

2021-10-04 01:06 UTC, SizableShrimp commented
Should be ready for re-review now.

2021-10-04 07:22 UTC, Harleyoc1 approved these changes, later dismissed

2021-10-09 10:20 UTC, sciwhiz12 submitted a review, later dismissed

2021-10-09 10:24 UTC, sciwhiz12 approved these changes

2021-10-09 10:24 UTC, merged