net.minecraft.client.*
ParchmentMC/Parchment pull request #73
Opened 2021-10-07 19:26 UTC by MelanX

only classes in this package, no sub-package

2021-10-07 20:04 UTC, Harleyoc1 requested changes

2021-10-07 20:04 UTC, Harleyoc1 commented on data/net/minecraft/client/ComponentCollector.mapping
> +		ARG 1 formattedText
This is added to a list called `parts`. 
```suggestion
		ARG 1 part
```

2021-10-07 20:04 UTC, Harleyoc1 commented on data/net/minecraft/client/HotbarManager.mapping
> +		ARG 1 directory
```suggestion
		ARG 1 gameDirectory
```

2021-10-07 20:04 UTC, Harleyoc1 commented on data/net/minecraft/client/Minecraft.mapping
> +		ARG 2 launchedVersion
(field name from `GameConfig$GameData`)
```suggestion
		ARG 2 launchVersion
```

2021-10-07 20:04 UTC, Harleyoc1 commented on data/net/minecraft/client/Minecraft.mapping
> +		ARG 3 launchedVersion
```suggestion
		ARG 3 launchVersion
```

2021-10-07 20:04 UTC, Harleyoc1 commented on data/net/minecraft/client/MouseHandler.mapping
> +		ARG 1 handle
```suggestion
		ARG 1 windowPointer
```

2021-10-07 20:04 UTC, Harleyoc1 commented on data/net/minecraft/client/MouseHandler.mapping
> +		ARG 1 handle
```suggestion
		ARG 1 windowPointer
```

2021-10-07 20:04 UTC, Harleyoc1 commented on data/net/minecraft/client/MouseHandler.mapping
> +		ARG 1 handle
```suggestion
		ARG 1 windowPointer
```

2021-10-07 20:04 UTC, Harleyoc1 commented on data/net/minecraft/client/MouseHandler.mapping
> +		ARG 1 window
```suggestion
		ARG 1 windowPointer
```

2021-10-07 20:04 UTC, Harleyoc1 commented on data/net/minecraft/client/Screenshot.mapping
> +		ARG 1 directory
```suggestion
		ARG 1 gameDirectory
```

2021-10-07 20:38 UTC, MelanX commented on data/net/minecraft/client/MouseHandler.mapping
> +		ARG 1 window
I can't make this `windowPointer`, otherwise the the lambas would break.

2021-10-08 13:13 UTC, alcatrazEscapee commented on data/net/minecraft/client/MouseHandler.mapping
> +		ARG 1 window
While it would generally be good practice not to name something the same as a lambda, the specific question, "will it break", is false. Forge doesn't include lambda parameters for this very reason (because they need recompileability), and Fabric doesn't need recompilability so "It will break" doesn't mean anything.

2021-10-08 13:44 UTC, MelanX commented on data/net/minecraft/client/MouseHandler.mapping
> +		ARG 1 window
Ahh good to know. Then I'll add it.

2021-10-08 14:20 UTC, Harleyoc1 requested changes
A couple other minor suggestions, rest looks good.

2021-10-08 14:20 UTC, Harleyoc1 commented on data/net/minecraft/client/MouseHandler.mapping
> +		ARG 5 mods
```suggestion
		ARG 5 modifiers
```

2021-10-08 14:20 UTC, Harleyoc1 commented on data/net/minecraft/client/MouseHandler.mapping
> +		ARG 5 yoffset
```suggestion
		ARG 3 xOffset
		ARG 5 yOffset
```

2021-10-08 14:20 UTC, Harleyoc1 commented on data/net/minecraft/client/MouseHandler.mapping
> +		ARG 5 ypos
```suggestion
		ARG 3 xPos
		ARG 5 yPos
```

2021-10-08 15:59 UTC, MelanX commented on data/net/minecraft/client/MouseHandler.mapping
> +		ARG 5 ypos
Can't change this according to the [convention on parameter names](https://github.com/ParchmentMC/Parchment/wiki/Mapping-Conventions#parameter-names-conventions) :/

2021-10-10 00:10 UTC, Harleyoc1 submitted a review, later dismissed

2021-10-12 18:00 UTC, Harleyoc1 approved these changes

2021-10-12 19:34 UTC, alcatrazEscapee approved these changes

2021-10-15 03:19 UTC, merged