net.minecraft.client.color.*
ParchmentMC/Parchment pull request #74
Opened 2021-10-07 19:35 UTC by MelanX

Both sub-packages included

2021-10-07 19:41 UTC, Harleyoc1 requested changes

2021-10-07 19:41 UTC, Harleyoc1 commented on data/net/minecraft/client/color/block/BlockColor.mapping
> +		ARG 3 blockPos
(recommendation for this and all lambda implementations in `BlocksColors`)
```suggestion
		ARG 1 state
		ARG 2 level
		ARG 3 pos
```

2021-10-08 06:05 UTC, sciwhiz12 requested changes

2021-10-08 06:05 UTC, sciwhiz12 commented on data/net/minecraft/client/color/block/BlockColor.mapping
> +		ARG 2 lightReader
The class here is `BlockAndTintGetter`, so I'm not sure `lightReader` is appropriate here. Might be best to follow @Harleyoc1's suggestion of `level` (and don't forget to change it for the subclasses, too).

2021-10-08 14:15 UTC, Harleyoc1 approved these changes

2021-10-08 15:26 UTC, sciwhiz12 approved these changes

2021-10-12 23:36 UTC, merged