some packages in net.minecraft.client.gui
ParchmentMC/Parchment pull request #75
Opened 2021-10-07 19:53 UTC by MelanX

net.minecraft.client.gui.chat.*
net.minecraft.client.gui.font.*
net.minecraft.client.gui.narration.*

2021-10-08 06:23 UTC, sciwhiz12 submitted a review, later dismissed

2021-10-08 06:36 UTC, OrionDevelopment submitted a review, later dismissed
Some minor things with the bakedglyph using index arguments instead of proper names.
But this looks okey for the rest.

2021-10-08 06:36 UTC, marchermans commented on data/net/minecraft/client/gui/font/glyphs/BakedGlyph.mapping
> +		ARG 7 v1
This needs proper naming
What is u0 and u1?
Why are they indexed.....

2021-10-08 06:36 UTC, marchermans commented on data/net/minecraft/client/gui/font/glyphs/BakedGlyph.mapping
> +			ARG 4 y1
Same here. Don't use index arguments if you can properly describe what they do

2021-10-08 07:40 UTC, sciwhiz12 commented on data/net/minecraft/client/gui/font/glyphs/BakedGlyph.mapping
> +		ARG 7 v1
This is because these parameters are directly assigned to fields, and according to the [convention on parameter names](https://github.com/ParchmentMC/Parchment/wiki/Mapping-Conventions#parameter-names-conventions), parameters which are directly assigned to fields should be named the same.
So we either break that convention here (which I suggest against), or add clarifying javadocs as to what each parameter is.

2021-10-08 13:02 UTC, MelanX commented on data/net/minecraft/client/gui/font/glyphs/BakedGlyph.mapping
> +		ARG 7 v1
I'm too unsure what the parameters are exactly for, sorry.

2021-10-08 14:29 UTC, Harleyoc1 commented on data/net/minecraft/client/gui/font/glyphs/BakedGlyph.mapping
> +		ARG 7 v1
They are sprite sheet x/y coordinates for the glyph texture. i.e. u0 and u1 are effectively min and max x coords for the glyph, etc.

2021-10-16 15:33 UTC, Harleyoc1 requested changes
Also want to re-iterate Sciwhiz's suggestion to add clarifying Javadoc to the `BakedGlyph` min/max sprite sheet coords.

2021-10-16 15:33 UTC, Harleyoc1 commented on data/net/minecraft/client/gui/chat/NarratorChatListener.mapping
>  		ARG 1 msg
Should be changed to `message`, especially since you mapped its overload to `message`.

2021-10-16 15:33 UTC, Harleyoc1 commented on data/net/minecraft/client/gui/narration/NarrationElementOutput.mapping
> +		ARG 2 contents
Overloads could be mapped (with the same names).

2021-11-14 18:22 UTC, Harleyoc1 requested changes

2021-11-14 18:22 UTC, Harleyoc1 commented on data/net/minecraft/client/gui/font/glyphs/BakedGlyph.mapping
> +			COMMENT maxY position of the glyph texture
Seems strange to use `minX`, `maxX`, etc if they don't refer to variable names. I'd suggest rewording all of these to `min/max x/y coordinate` (`of the glyph texture` is also redundant).

2021-11-20 18:07 UTC, Harleyoc1 approved these changes

2021-12-02 20:44 UTC, alcatrazEscapee approved these changes

2021-12-05 01:26 UTC, merged