additional work on net.minecraft.client.gui.components.*
ParchmentMC/Parchment pull request #76
Opened 2021-10-07 20:28 UTC by MelanX

Tried to look at #50 to not change stuff it added.

2021-10-08 06:14 UTC, sciwhiz12 submitted a review, later dismissed

2021-10-08 06:38 UTC, OrionDevelopment submitted a review, later dismissed
Some minor nitpickings and questions. Looks good otherwise though

2021-10-08 06:38 UTC, marchermans commented on data/net/minecraft/client/gui/components/AbstractSelectionList.mapping
> +		ARG 1 x0
Don't use indexed arguments. Name them properly

2021-10-08 06:38 UTC, marchermans commented on data/net/minecraft/client/gui/components/AbstractSelectionList.mapping
> +		ARG 2 y
If this is the mouse position, then the word "mouse" needs to be prefixed, see other locations in this file for examples.

2021-10-08 06:38 UTC, marchermans commented on data/net/minecraft/client/gui/components/CommandSuggestions.mapping
> +			ARG 5 suggestionList
Any idea what the other arguments are? Or are they mapped from super types?

2021-10-08 07:41 UTC, sciwhiz12 commented on data/net/minecraft/client/gui/components/AbstractSelectionList.mapping
> +		ARG 1 x0
This is because these parameters are directly assigned to fields, and according to the [convention on parameter names](https://github.com/ParchmentMC/Parchment/wiki/Mapping-Conventions#parameter-names-conventions), parameters which are directly assigned to fields should be named the same.
So we either break that convention here (which I suggest against), or add clarifying javadocs as to what each parameter is.

2021-10-08 12:52 UTC, MelanX commented on data/net/minecraft/client/gui/components/CommandSuggestions.mapping
> +			ARG 5 suggestionList
True, looking a bit more detailed on it the other arguments are easy.

2021-10-08 13:02 UTC, MelanX commented on data/net/minecraft/client/gui/components/AbstractSelectionList.mapping
> +		ARG 1 x0
I'm too unsure what the parameters are exactly for, sorry.

2021-10-08 14:40 UTC, Harleyoc1 commented on data/net/minecraft/client/gui/components/AbstractSelectionList.mapping
> +		ARG 1 x0
It's just resetting the x-coordinates based on a given position relative to the left side of the screen. Whilst it is assigned to the field `x0` it is also used to calculate `x1` so `left` or `x` is an acceptable name IMO.

2021-10-16 19:50 UTC, Harleyoc1 requested changes

2021-10-16 19:50 UTC, Harleyoc1 commented on data/net/minecraft/client/gui/components/spectator/SpectatorGui.mapping
> +		ARG 2 partialTicks
Might want to do a full search and replace on this PR too. 
```suggestion
		ARG 2 partialTick
```

2021-10-16 19:50 UTC, Harleyoc1 commented on data/net/minecraft/client/gui/components/toasts/Toast.mapping
> +		ARG 3 lastChanged
I would recommend also adding Javadoc to clarify that it's in milliseconds (or call it `millisSinceLastVisible`). 
```suggestion
		ARG 3 timeSinceLastVisible
```

2021-11-14 18:19 UTC, Harleyoc1 approved these changes

2021-11-14 23:37 UTC, sciwhiz12 approved these changes

2021-12-02 20:47 UTC, merged