net.minecraft.client.gui.screens.*
ParchmentMC/Parchment pull request #77
Opened 2021-10-07 21:15 UTC by MelanX

Only the main packages because there were so many. Sub-packages in seperate PR.
Could be conflicting with #76 because of the one matrixStack -> poseStack. I don't know exactly why this was changed.

2021-10-10 00:05 UTC, Harleyoc1 requested changes

2021-10-10 00:05 UTC, Harleyoc1 commented on data/net/minecraft/client/gui/screens/AccessibilityOptionsScreen.mapping
> +		ARG 1 button
Might be nice if these were named by what their button was so their function is instantly recognisable, i.e. `openGuideButton`, `doneButton`, etc (echo for other button lambdas if you do decide to do this).

2021-10-10 00:05 UTC, Harleyoc1 commented on data/net/minecraft/client/gui/screens/ConfirmLinkScreen.mapping
> +		ARG 2 url
Could add the remaining boolean param here; my suggestion is `trusted`.

2021-10-10 00:05 UTC, Harleyoc1 commented on data/net/minecraft/client/gui/screens/CreateBuffetWorldScreen.mapping
> +		ARG 2 registry
This isn't a registry in itself, it provides access to registries. 
```suggestion
		ARG 2 registryAccess
```

2021-10-10 00:05 UTC, Harleyoc1 commented on data/net/minecraft/client/gui/screens/PresetFlatWorldScreen.mapping
> +		ARG 1 currentLayers
This appears to be the current height, as opposed to the number of layers.
```suggestion
		ARG 1 currentHeight
```

2021-10-10 00:05 UTC, Harleyoc1 commented on data/net/minecraft/client/gui/screens/PresetFlatWorldScreen.mapping
> +		ARG 0 setting
`string` or `layerInfo` would be better.

2021-10-10 00:05 UTC, Harleyoc1 commented on data/net/minecraft/client/gui/screens/PresetFlatWorldScreen.mapping
> +		ARG 0 settings
Again, `string` or `layersInfo`.

2021-10-12 19:39 UTC, alcatrazEscapee approved these changes

2021-10-12 21:36 UTC, Harleyoc1 approved these changes

2021-10-15 03:19 UTC, merged