net.minecraft.client.gui.screens.* sub-packages
ParchmentMC/Parchment pull request #78
Opened 2021-10-07 22:19 UTC by MelanX

Contains all the sub-packages but .inventory.* because there are too many classes. Will put it in another PR.

2021-10-10 09:33 UTC, Harleyoc1 requested changes

2021-10-10 09:33 UTC, Harleyoc1 commented on data/net/minecraft/client/gui/components/AbstractSelectionList.mapping
> +			ARG 4 x
Why this change? Both these params are obtained from the methods `getRowTop` and `getRowLeft` respectively. `top` and `left` is more specific than `y` and `x`.

2021-10-10 09:33 UTC, Harleyoc1 commented on data/net/minecraft/client/gui/screens/controls/ControlList.mapping
> +		ARG 1 screen
(field name)
```suggestion
		ARG 1 controlsScreen
```

2021-10-10 09:33 UTC, Harleyoc1 commented on data/net/minecraft/client/gui/screens/debug/GameModeSwitcherScreen.mapping
> +			ARG 1 selected
(field name)
```suggestion
			ARG 1 isSelected
```

2021-10-10 09:33 UTC, Harleyoc1 commented on data/net/minecraft/client/gui/screens/multiplayer/JoinMultiplayerScreen.mapping
> +		ARG 1 entry
(following through to `AbstractSelectionList` field name)
```suggestion
		ARG 1 selected
```

2021-10-10 09:33 UTC, Harleyoc1 commented on data/net/minecraft/client/gui/screens/recipebook/GhostRecipe.mapping
> +		ARG 6 partialTicks
```suggestion
		ARG 6 partialTick
```

2021-10-10 09:33 UTC, Harleyoc1 commented on data/net/minecraft/client/gui/screens/recipebook/RecipeBookComponent.mapping
> +		ARG 5 partialTicks
```suggestion
		ARG 5 partialTick
```

2021-10-10 09:33 UTC, Harleyoc1 commented on data/net/minecraft/client/gui/screens/recipebook/RecipeBookPage.mapping
> +		ARG 6 partialTicks
```suggestion
		ARG 6 partialTick
```

2021-10-10 09:33 UTC, Harleyoc1 commented on data/net/minecraft/client/gui/screens/social/SocialInteractionsScreen.mapping
> +		ARG 1 lastSearch
This seems to be passed the new text when it's changed. 
```suggestion
		ARG 1 newText
```

2021-10-10 09:33 UTC, Harleyoc1 commented on data/net/minecraft/client/gui/screens/worldselection/CreateWorldScreen.mapping
> +		ARG 0 cycleButton
```suggestion
		ARG 0 modeButton
```
(or just `button`)

2021-10-10 09:33 UTC, Harleyoc1 commented on data/net/minecraft/client/gui/screens/worldselection/CreateWorldScreen.mapping
> +		ARG 1 selectedGameMode
(field name)
```suggestion
		ARG 1 gameMode
```

2021-10-10 09:33 UTC, Harleyoc1 commented on data/net/minecraft/client/gui/screens/worldselection/SelectWorldScreen.mapping
> +		ARG 1 tooltip
(field/method name)
```suggestion
		ARG 1 toolTip
```

2021-10-10 09:33 UTC, Harleyoc1 commented on data/net/minecraft/client/gui/screens/worldselection/WorldGenSettingsComponent.mapping
> +		ARG 0 cycleButton
```suggestion
		ARG 0 featuresButton
```
(or just `button`)

2021-10-10 09:33 UTC, Harleyoc1 commented on data/net/minecraft/client/gui/screens/worldselection/WorldGenSettingsComponent.mapping
> +		ARG 0 cycleButton
```suggestion
		ARG 0 typeButton
```
(or just `button`)

2021-10-10 09:33 UTC, Harleyoc1 commented on data/net/minecraft/client/gui/screens/worldselection/WorldGenSettingsComponent.mapping
> +		ARG 2 cycleButton
```suggestion
		ARG 2 typeButton
```
(or just `button`)

2021-10-10 09:33 UTC, Harleyoc1 commented on data/net/minecraft/client/gui/screens/worldselection/WorldGenSettingsComponent.mapping
> +		ARG 0 seed
Whilst it does only seem to be used for the seed, this method could be used to parse any long. There is nothing that specifically ties it to the seed.

2021-10-10 09:33 UTC, Harleyoc1 commented on data/net/minecraft/client/gui/screens/worldselection/WorldPreset.mapping
> +		ARG 0 registry
```suggestion
		ARG 0 registryAccess
```

2021-10-10 09:33 UTC, Harleyoc1 commented on data/net/minecraft/client/gui/screens/worldselection/WorldPreset.mapping
> +		ARG 0 registry
```suggestion
		ARG 0 registryAccess
```

2021-10-10 20:44 UTC, MelanX commented on data/net/minecraft/client/gui/components/AbstractSelectionList.mapping
> +			ARG 4 x
I think this happened because I changed `EditGameRulesScreen$IntegerRuleEntry#render` and this also changed this. I did not change anything else in `net.minecraft.client.gui.*` in this PR, so this was a change which was made somewhere else.

2021-10-10 20:48 UTC, MelanX commented on data/net/minecraft/client/gui/screens/recipebook/GhostRecipe.mapping
> +		ARG 6 partialTicks
Everywhere else it's `partialTicks`, why changing it here to without s?

2021-10-10 20:56 UTC, MelanX commented on data/net/minecraft/client/gui/screens/worldselection/WorldGenSettingsComponent.mapping
> +		ARG 0 seed
Whatever you type in will be used as seed. This method is private and only be called in `WorldGenSettingsComponent#parseSeed`. That's why I called this seed.

2021-10-10 21:10 UTC, Harleyoc1 commented on data/net/minecraft/client/gui/screens/recipebook/GhostRecipe.mapping
> +		ARG 6 partialTicks
My knowledge is that `partialTick` should be preferred as it lines up better with Mojang method names in various places. This is a bit like `matrixStack` being in a lot of places; they're remnants of the MCP base.

2021-10-10 21:14 UTC, Harleyoc1 commented on data/net/minecraft/client/gui/screens/worldselection/WorldGenSettingsComponent.mapping
> +		ARG 0 seed
Someone from the team/standards should probably comment on this. My opinion is that there is no need for it to be specific in the context of a generic method that could theoretically be used to parse any long (with nothing tying it to the seed outside it being the only use).

2021-10-10 21:59 UTC, Lanse505 commented on data/net/minecraft/client/gui/screens/worldselection/WorldGenSettingsComponent.mapping
> +		ARG 0 seed
I'd say call it "parsableLong" or something like that, the context around upward call members in the line isnt really what should be applied to the bottom member method.

I dont have the code infront of me but from the name it seems to parse a long value into "something".
And hence call it "parsableLong" or something akin to it, since you're passing in a long to be parsed.

2021-10-12 17:40 UTC, Harleyoc1 commented
Since you've decided to change all of the `partialTick` parameter you may as well do a search and replace for the remaining `matrixStack` parameters in these packages too. I can see a few still in the same methods in which `partialTick` was changed in that last commit.

2021-10-12 17:41 UTC, MelanX commented
Oh, I thought I fixed that, too. Will search again.

2021-10-12 17:43 UTC, Harleyoc1 commented on data/net/minecraft/client/gui/components/AbstractSelectionList.mapping
> +			ARG 4 x
Should probably just remove all changes from this file and handle the other changes in your `net.minecraft.client.gui.*` PR to avoid conflicts.

2021-10-12 21:37 UTC, Harleyoc1 submitted a review, later dismissed

2021-10-20 23:05 UTC, alcatrazEscapee requested changes
One thing I caught, looks like a typo?

2021-10-20 23:05 UTC, alcatrazEscapee commented on data/net/minecraft/client/gui/screens/worldselection/WorldGenSettingsComponent.mapping
> +		ARG 0 s
`seed` ?

2021-11-14 15:04 UTC, alcatrazEscapee approved these changes

2021-11-14 18:16 UTC, Harleyoc1 approved these changes

2021-12-02 20:50 UTC, merged