net.minecraft.client.gui.screens.inventory.*
ParchmentMC/Parchment pull request #79
Opened 2021-10-08 13:42 UTC by MelanX

PR mentioned in #78

2021-10-10 09:51 UTC, Harleyoc1 requested changes

2021-10-10 09:51 UTC, Harleyoc1 commented on data/net/minecraft/client/gui/screens/inventory/AbstractCommandBlockEditScreen.mapping
> +		ARG 1 cycleButton
```suggestion
		ARG 1 outputButton
```
(or just `button`)

2021-10-10 09:51 UTC, Harleyoc1 commented on data/net/minecraft/client/gui/screens/inventory/AbstractFurnaceScreen.mapping
> +		ARG 1 imageButton
```suggestion
		ARG 1 recipeButton
```

2021-10-10 09:51 UTC, Harleyoc1 commented on data/net/minecraft/client/gui/screens/inventory/BookEditScreen.mapping
> +		ARG 1 signed
`signed` suggests the current state where this is only true if the book is being signed. `saveChanges` param should also be updated. 
```suggestion
		ARG 1 sign
```

2021-10-10 09:51 UTC, Harleyoc1 commented on data/net/minecraft/client/gui/screens/inventory/BookViewScreen.mapping
> +			ARG 1 stack
```suggestion
			ARG 1 writtenBookStack
```

2021-10-10 09:51 UTC, Harleyoc1 commented on data/net/minecraft/client/gui/screens/inventory/BookViewScreen.mapping
> +			ARG 0 stack
```suggestion
			ARG 0 writtenBookStack
```

2021-10-10 09:51 UTC, Harleyoc1 commented on data/net/minecraft/client/gui/screens/inventory/BookViewScreen.mapping
> +			ARG 1 stack
```suggestion
			ARG 1 writableBookStack
```

2021-10-10 09:51 UTC, Harleyoc1 commented on data/net/minecraft/client/gui/screens/inventory/BookViewScreen.mapping
> +			ARG 0 stack
```suggestion
			ARG 0 writableBookStack
```

2021-10-10 09:51 UTC, Harleyoc1 commented on data/net/minecraft/client/gui/screens/inventory/CraftingScreen.mapping
> +		ARG 1 imageButton
```suggestion
		ARG 1 recipeButton
```

2021-10-10 09:51 UTC, Harleyoc1 commented on data/net/minecraft/client/gui/screens/inventory/InventoryScreen.mapping
> +		ARG 1 imageButton
```suggestion
		ARG 1 recipeButton
```

2021-10-10 09:51 UTC, Harleyoc1 commented on data/net/minecraft/client/gui/screens/inventory/JigsawBlockEditScreen.mapping
> +		ARG 1 cycleButton
```suggestion
		ARG 1 keepJigsawsButton
```
(or just `button`)

2021-10-10 09:51 UTC, Harleyoc1 commented on data/net/minecraft/client/gui/screens/inventory/StructureBlockEditScreen.mapping
> +		ARG 1 cycleButton
```suggestion
		ARG 1 modeButton
```
(or just `button`)

2021-10-12 21:33 UTC, Harleyoc1 approved these changes

2021-10-13 22:54 UTC, alcatrazEscapee approved these changes

2021-10-20 22:56 UTC, merged