last packages in net.minecraft.client.gui.*
ParchmentMC/Parchment pull request #80
Opened 2021-10-08 14:17 UTC by MelanX

net.minecraft.client.gui.*
net.minecraft.client.gui.spectator.*

2021-10-12 18:16 UTC, MelanX commented
Was in the wrong branch for the changes I made, because of this I force pushed it to revert it... I hoped that you wouldn't see my mistake then :D

2021-10-16 20:11 UTC, Harleyoc1 requested changes

2021-10-16 20:11 UTC, Harleyoc1 commented on data/net/minecraft/client/gui/Font.mapping
> +		ARG 1 component
This is called `text` in all other overloads as well as alternate `draw` methods in this class. 
```suggestion
		ARG 1 text
```

2021-10-16 20:11 UTC, Harleyoc1 commented on data/net/minecraft/client/gui/Font.mapping
> +		ARG 7 bugger
lol
```suggestion
		ARG 7 bufferSource
```
Should also be reflected in overloads for those named `buffer` that are a buffer source.

2021-10-16 20:11 UTC, Harleyoc1 commented on data/net/minecraft/client/gui/Font.mapping
> +		ARG 9 colorBackground
This is minor, but unless there's a good reason not to (i.e. a field name) I would change these to `backgroundColor`.

2021-10-16 20:11 UTC, Harleyoc1 commented on data/net/minecraft/client/gui/Font.mapping
> +		ARG 4 maxLength
(field name of `StringSplitter$LineBreakFinder`)
```suggestion
		ARG 4 maxWidth
```

2021-10-16 20:11 UTC, Harleyoc1 commented on data/net/minecraft/client/gui/Font.mapping
> +		ARG 2 maxLength
(field name of StringSplitter$LineBreakFinder)
```suggestion
		ARG 2 maxWidth
```

2021-10-16 20:11 UTC, Harleyoc1 commented on data/net/minecraft/client/gui/Gui.mapping
> +		ARG 3 id
`senderId` or `playerId`

2021-10-16 20:11 UTC, Harleyoc1 commented on data/net/minecraft/client/gui/Gui.mapping
> +		ARG 2 xPos
```suggestion
		ARG 2 x
```

2021-10-16 20:11 UTC, Harleyoc1 commented on data/net/minecraft/client/gui/MapRenderer.mapping
> +		ARG 2 buffer
```suggestion
		ARG 2 bufferSource
```

2021-10-16 20:11 UTC, Harleyoc1 commented on data/net/minecraft/client/gui/MapRenderer.mapping
>  			ARG 2 buffer
```suggestion
			ARG 2 bufferSource
```

2021-10-16 20:11 UTC, Harleyoc1 commented on data/net/minecraft/client/gui/spectator/categories/TeleportToPlayerMenuCategory.mapping
> +		ARG 1 playerInfos
```suggestion
		ARG 1 players
```

2021-11-14 18:24 UTC, Harleyoc1 approved these changes

2021-11-30 17:54 UTC, sciwhiz12 approved these changes

2021-12-02 20:51 UTC, merged