net.minecraft.client.model.*
ParchmentMC/Parchment pull request #81
Opened 2021-10-08 15:14 UTC by MelanX

2021-10-21 09:29 UTC, Harleyoc1 requested changes

2021-10-21 09:29 UTC, Harleyoc1 commented on data/net/minecraft/client/model/AgeableListModel.mapping
> +		ARG 4 babyZHeadScale
```suggestion
		ARG 4 babyZHeadOffset
```

2021-10-21 09:29 UTC, Harleyoc1 commented on data/net/minecraft/client/model/AgeableListModel.mapping
> +		ARG 3 babyZHeadScale
```suggestion
		ARG 3 babyZHeadOffset
```

2021-10-21 09:29 UTC, Harleyoc1 commented on data/net/minecraft/client/model/AgeableListModel.mapping
> +		ARG 3 babyZHeadScale
```suggestion
		ARG 3 babyZHeadOffset
```

2021-10-21 09:29 UTC, Harleyoc1 commented on data/net/minecraft/client/model/dragon/DragonHeadModel.mapping
> +		ARG 1 modelPart
```suggestion
		ARG 1 root
```

2021-11-14 18:17 UTC, Harleyoc1 approved these changes

2021-12-02 20:54 UTC, alcatrazEscapee approved these changes

2021-12-05 01:27 UTC, merged