Phoenix: levelgen/feature/structure, levelgen/structure/*
ParchmentMC/Parchment pull request #89
Opened 2021-10-13 21:41 UTC by alcatrazEscapee

- Invalid mappings dropped, and verified that any removals are populated again on export.
- Not a lot of mapping done since I don't really understand structures. **but**, the point was to audit and remove any lingering mcp cruft (e.g. `templateManager`), which I have done. And to finish up Phoenix for all of `levelgen`.
- I found bounding boxes were named `box`, `bb`, `sbb`, `boundingBox`, and `bounds`.

2021-10-22 03:16 UTC, sciwhiz12 requested changes
One typo and a few blank comment lines, otherwise ready to :shipit:. I suggest running the data sanitation task (`sanitizeData`) to, among other effects, get rid of the blank comment lines automatically.

2021-10-22 03:16 UTC, sciwhiz12 commented on data/net/minecraft/world/level/levelgen/structure/BoundingBox.mapping
> +		ARG 0 steam
Typo:
```suggestion
		ARG 0 stream
```

2021-10-22 03:16 UTC, sciwhiz12 commented on data/net/minecraft/world/level/levelgen/structure/StructurePiece.mapping
> +			COMMENT
Remove the empty comment line, please.

2021-10-22 03:16 UTC, sciwhiz12 commented on data/net/minecraft/world/level/levelgen/structure/StructurePiece.mapping
> +		COMMENT
Remove the empty comment line, please.

2021-10-22 03:16 UTC, sciwhiz12 commented on data/net/minecraft/world/level/levelgen/structure/StructurePiece.mapping
> +		COMMENT
Remove the empty comment line, please.

2021-10-22 03:16 UTC, sciwhiz12 commented on data/net/minecraft/world/level/levelgen/structure/StructurePiece.mapping
> +		COMMENT
Remove the empty comment line, please.

2021-10-22 03:16 UTC, sciwhiz12 commented on data/net/minecraft/world/level/levelgen/structure/StructureStart.mapping
> +		COMMENT
Remove the empty comment line, please.

2021-10-22 03:16 UTC, sciwhiz12 commented on data/net/minecraft/world/level/levelgen/structure/templatesystem/AlwaysTrueTest.mapping
> -		ARG 2 random
Remove the file, as it is now empty.

2021-10-22 03:16 UTC, sciwhiz12 commented on data/net/minecraft/world/level/levelgen/structure/templatesystem/PosAlwaysTrueTest.mapping
> -		ARG 4 random
Remove the file, as it is now empty.

2021-10-31 21:12 UTC, sciwhiz12 submitted a review, later dismissed

2021-12-02 22:58 UTC, Harleyoc1 requested changes

2021-12-02 22:58 UTC, Harleyoc1 commented on data/net/minecraft/world/level/levelgen/structure/templatesystem/ProcessorRule.mapping
> +			COMMENT The local position of the target state, realitive to the structure origin.
```suggestion
			COMMENT The local position of the target state, relative to the structure origin.
```

2021-12-03 00:35 UTC, sciwhiz12 approved these changes

2021-12-05 11:16 UTC, Harleyoc1 approved these changes

2021-12-11 16:32 UTC, merged