Documented n.m.resources and n.m.core.RegistryAccess
ParchmentMC/Parchment pull request #92
Opened 2021-10-17 16:45 UTC by alcatrazEscapee

Also included: cleanup in `net.minecraft.resources` and `net.minecraft.core`, dropping some unused things that in a bunch of cases were hiding better javadocs from the superclass.

I can't tell if Mojang's registry codec madness is clever or if it is braindead after staring at it for too long, it's turning my brain into mush. My best guess is that it is both, in equal proportion.

2021-10-17 18:34 UTC, ChampionAsh5357 requested changes
Mostly just inconsistencies and misspellings between documentation lines.

Any `@param`, `@return`, or `@throws` tag should start with an lowercased first world with no punctuation (e.g. period, explanation mark) at the end of the line.

2021-10-17 18:34 UTC, ChampionAsh5357 commented on data/net/minecraft/core/RegistryAccess.mapping
> +		COMMENT When this class is loaded, this registry holder is initialized, which involves copying all elements from the builtin registries at {@link net.minecraft.data.BuiltinRegistries} into this fie
Extra `}.` at the end.

2021-10-17 18:34 UTC, ChampionAsh5357 commented on data/net/minecraft/core/RegistryAccess.mapping
>  		ARG 1 registryKey
Inconsistent scheme with `#registryOrThrow`

2021-10-17 18:34 UTC, ChampionAsh5357 commented on data/net/minecraft/core/RegistryAccess.mapping
>  		ARG 1 registryKey
Inconsistent scheme with `#ownedRegistryOrThrow`

2021-10-17 18:34 UTC, ChampionAsh5357 commented on data/net/minecraft/core/RegistryAccess.mapping
> +		COMMENT Creates a new registry holder which includes all default dynamic registries.
Not really a class level comment, probably was for `<init>` instead.

2021-10-17 18:34 UTC, ChampionAsh5357 commented on data/net/minecraft/resources/RegistryReadOps.mapping
> +			COMMENT An in-memory, JSON serialized form of a {@link net.minecraft.coreRegistryAccess}.
`core.RegistryAccess`.

2021-10-17 18:34 UTC, ChampionAsh5357 commented on data/net/minecraft/resources/RegistryReadOps.mapping
> +			COMMENT It retains integer ID and lifecycles of every registry element, and is used to bridge the gap between {@link RegistryReadOps} and {@link net.minecraft.resources.RegistryWriteOps} when usin
It retains the integer IDs and lifecycles...

2021-10-17 18:41 UTC, alcatrazEscapee commented on data/net/minecraft/core/RegistryAccess.mapping
> +		COMMENT Creates a new registry holder which includes all default dynamic registries.
I blame Enigma for this one, it's constructor docs have been betraying me lately.

2021-10-17 18:42 UTC, Harleyoc1 commented on data/net/minecraft/core/RegistryAccess.mapping
> +		COMMENT Creates a new registry holder which includes all default dynamic registries.
Yeah that was probably Enigma. I've seen it do exactly the same thing before.

2021-10-17 20:17 UTC, ChampionAsh5357 approved these changes

2021-10-22 02:43 UTC, sciwhiz12 approved these changes

2021-10-25 01:10 UTC, merged