Mapped some parameters in BlockGetter
ParchmentMC/Parchment pull request #93
Opened 2021-10-20 07:54 UTC by tmvkrpxl0

`belowShapeSupplier` is guessed parameter name. All use cases for this was providing collision shape of block below another shape that is provided in first argument. I'm not sure what to name this
`traverseContext` and `traversePos` is repeatedly provided to `test` BiFunction in while loop in `traverseBlock`. `traversePos` is temporary position in this context. Since those 2 are being used when traversing block, I think this shouldn't just be `pos` or `context` because of that.
I'm not sure what to name `tester` and `onFail`. When traversing block, `tester` is repeatedly used to determine to see if it hit block. and `onFail` is executed when it misses.

2021-10-20 13:29 UTC, alcatrazEscapee requested changes

2021-10-20 13:29 UTC, alcatrazEscapee commented on data/net/minecraft/world/level/BlockGetter.mapping
> +		COMMENT This uses Collision shape of provided block.
```suggestion
		COMMENT This uses the collision shape of provided block.
```

2021-10-20 23:38 UTC, alcatrazEscapee approved these changes

2021-10-21 00:17 UTC, sciwhiz12 approved these changes

2021-10-22 02:31 UTC, merged